import { createGothicProject } from './gothic-app.js?v=arch-stream-2';
import { course, materials, preparation } from './data.js';
const main = document.querySelector('main');
const status = document.querySelector('#save-status');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let profile; try { profile = JSON.parse(sessionStorage.getItem('fei_user_profile') || 'null'); } catch {}
const identity = profile?.supabaseUserId || profile?.studentCode || profile?.email || 'guest';
const key = 'fei_remake_cardboard_v1:' + identity;
let state = { responses:{}, started:[], completed:[], positions:{} };
try { const saved = JSON.parse(localStorage.getItem(key)); if(saved && typeof saved.responses==='object' && saved.responses && Array.isArray(saved.started) && Array.isArray(saved.completed) && saved.positions) state=saved; } catch {}
function save(){try{localStorage.setItem(key,JSON.stringify(state));status.textContent='Saved in this browser · download notes to keep a copy.';}catch{status.textContent='Browser saving unavailable. Download your notes before leaving.';}}
const response = id => state.responses[id] ?? '';
const field = (id,label) => `<label class="field">${esc(label)}<textarea data-response="${esc(id)}" placeholder="Your thoughts…">${esc(response(id))}</textarea></label>`;
const check = (id,label) => `<label class="check"><input type="checkbox" data-response="${esc(id)}" ${response(id)===true?'checked':''}><span>${esc(label)}${label==='Craft knife'?'<strong class="safety">Adult supervision required</strong>':''}</span></label>`;
function media(a){if(!a)return '';if(a.src){if(a.kind==='download')return `<a class="btn secondary" href="${esc(a.src)}" download>${esc(a.label)}</a>`;return `<figure class="media">${a.kind==='video'?`<video controls preload="metadata" aria-label="${esc(a.label)}" src="${esc(a.src)}"></video>`:`<img src="${esc(a.src)}" alt="${esc(a.alt)}" loading="lazy">`}<figcaption>${esc(a.label)}</figcaption></figure>`;}return `<div class="media" data-asset="${esc(a.id)}"><small>${esc(a.kind)} placeholder</small><strong>${esc(a.label)}</strong><small>Teacher content to come</small></div>`;}
const link=(href,label,secondary=false)=>`<a class="btn ${secondary?'secondary':''}" href="${href}">${esc(label)}</a>`;
const route=(n,step)=>`#lesson/${n}/${step || state.positions[n] || course.lessons[n-1].screens[0].screenId}`;
function toolCard(m, id) {
 return `<label class="tool-card ${response(id)===true?'is-ready':''}"><input type="checkbox" aria-label="${esc(m.name + (m.safety ? ": " + m.safety : ""))}" data-response="${esc(id)}" ${response(id)===true?'checked':''}><span class="ready-mark" aria-hidden="true">✓</span><img src="${esc(m.image.src)}" alt="${esc(m.name)}" loading="lazy"><span class="tool-name">${esc(m.name)}</span>${m.safety?`<span class="tool-safety">${esc(m.safety)}</span>`:''}</label>`;
}
function materialBoard(part){
 const basicIds={pencil:'prepare-1-0',scissors:'prepare-1-3',glue:'prepare-1-4'};
 const optionalIds={mat:'prepare-2-1',knife:'prepare-2-2','hot-glue':'prepare-hot-glue'};
 const board=`<section class="gather-block"><div class="action-heading"><span class="action-number">01</span><div><h2>Find some cardboard</h2><p>Clean, dry packaging. Different thicknesses.</p></div></div><div class="cardboard-pick"><img src="${esc(course.cover.src)}" alt="Reused corrugated cardboard and thin white packaging collected at home"><div>${preparation[0].items.map((t,j)=>check('prepare-0-'+j,t)).join('')}</div></div></section>
 <section class="gather-block"><div class="action-heading"><span class="action-number">02</span><div><h2>Pick your tools</h2><p>Tap a picture when it’s ready.</p></div></div><div class="tool-grid">${materials.filter(m=>basicIds[m.id]).map(m=>toolCard(m,basicIds[m.id])).join('')}</div><p class="small-note">Any suitable craft glue works — UHU is shown here.</p><div class="also-bring"><b>Also bring</b>${[['prepare-1-1','Ruler'],['prepare-1-2','Eraser'],['prepare-1-5','Masking tape']].map(([id,t])=>check(id,t)).join('')}</div></section>
 <details class="optional-tools"><summary>Optional tools <span>For later / with an adult</span></summary><div class="tool-grid">${materials.filter(m=>optionalIds[m.id]).map(m=>toolCard(m,optionalIds[m.id])).join('')}</div><div class="also-bring">${check('prepare-2-0','Tracing paper')}${check('prepare-2-3','Colored translucent material')}</div><p class="safety">Craft knife and hot glue gun: adult supervision required. Use a cutting mat for knife work.</p></details>
 <details class="photo-reference"><summary>See the whole tool setup</summary>${media({id:'materials-flatlay',src:'assets/materials-flatlay.jpg',alt:'Teacher’s pencils, capped craft knife, scissors, hot glue gun and UHU glue on a gridded board',label:'Your teacher’s setup · you don’t need every tool',kind:'image'})}</details>`;
 if(!part)return board;
 const split=board.indexOf('<section class="gather-block">',20);
 return part==='cardboard'?board.slice(0,split):board.slice(split,board.indexOf('<details class="optional-tools">'));
}
function overview(){
 main.innerHTML=`<div class="project-top"><a href="../../index.html?view=material-art">← Material Art</a><span>SMART CLASS</span></div><header class="path-heading"><div class="eyebrow">Material Design</div><h1>RE:MAKE 01<br>Cardboard</h1><p>Choose your learning path.</p></header><a class="course-choice" href="#project/gothic"><img src="assets/gothic/project-map.png" alt="Gothic cardboard building project"><span><small>READY TO MAKE · 7 SECTIONS</small><h2>Build a Gothic-inspired Cathedral</h2><p>Open learning path →</p></span></a><details class="course-details"><summary>Explore the full cardboard course · 6 lessons</summary><ol class="course-list">${course.lessons.map(l=>`<li><a href="${route(l.number)}"><strong>${l.title}</strong><span>${state.completed.includes(l.lessonId)?'Complete ✓':'Open →'}</span></a></li>`).join('')}</ol></details>`;
}

function prepare(){main.innerHTML=`<a href="#overview">← Course overview</a><header class="prepare-heading"><div class="eyebrow">Before lesson 1</div><h1>Gather. Then make.</h1><p>Find it. Tap it. You’re ready.</p></header>${materialBoard()}<div class="ready-bar"><span>Got the basics? Let’s explore.</span>${link(route(1,'question'),'I’M READY →')}</div>`;}
function content(s,l){const prefix=`${l.lessonId}:${s.screenId}:`;let html=s.type==='materials'?'':media(s.image)+media(s.diagram)+media(s.download)+(s.video?`<details class="photo-reference"><summary>${s.video.src?'Watch the teacher demo':'Teacher video · coming soon'}</summary>${media(s.video)}</details>`:'');
 if(l.number===2||l.number===5)html+=`<p><a href="#project/gothic">Open the Gothic cardboard example →</a></p>`;
 if(s.discussionQuestion)html+=`<p class="notice">${esc(s.discussionQuestion)}</p>`;
 if(s.body)html+=`<p>${esc(s.body)}</p>`;
 if(s.type==='materials')html+=materialBoard();
 if(s.tests)html+=`<div class="grid">${s.tests.map((t,i)=>`<article class="card"><div class="eyebrow">TEST 0${i+1}</div><h3>${t.title}</h3><p>${t.question}</p>${media(t.media)}<p>${t.instruction}</p>${field(prefix+t.id+'-before','BEFORE · '+t.prediction)}<button class="chip" data-toggle="${prefix+t.id+'-try'}" aria-pressed="${response(prefix+t.id+'-try')===true}">${response(prefix+t.id+'-try')?'Trying it ✓':'Try It'}</button>${field(prefix+t.id+'-after','AFTER · What happened?')}</article>`).join('')}</div>`;
 if(s.choices)html+=`<div class="chips">${s.choices.map(c=>`<button class="chip" data-choice="${esc(prefix+'choices')}" data-value="${esc(c)}" data-single="${s.type==='choice'}" aria-pressed="${Array.isArray(response(prefix+'choices'))&&response(prefix+'choices').includes(c)}">${esc(c)}</button>`).join('')}</div>`;
 if(s.elements)html+=s.elements.map(e=>`<article class="card"><h3>${e.title}</h3><div class="grid">${media(e.image)}${media(e.diagram)}</div><p class="muted">${e.explanation}</p>${field(prefix+e.id+'-observe',e.question)}${field(prefix+e.id+'-cardboard','How could we use this with cardboard?')}</article>`).join('');
 if(s.assets)html+=`<div class="grid">${s.assets.map(media).join('')}</div>`;
 if(s.constraints)html+=`<ul>${s.constraints.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`;
 if(s.items)html+=s.items.map((t,i)=>check(prefix+i,t)).join('');
 if(s.prompts)html+=s.prompts.map(p=>field(prefix+p.id,p.label)).join('');
 if(s.type==='quiz')html+='<p class="notice">Draft quick check · responses are saved, but not scored.</p>';
 if(s.type==='plan')html+=course.lessons[2].screens.filter(x=>x.choices||x.prompts).map(x=>{const p=`${l.lessonId}:${x.screenId}:`;return `<div class="summary"><b>${esc(x.title)}</b>${esc([...(Array.isArray(response(p+'choices'))?response(p+'choices'):[]),...(x.prompts||[]).map(q=>response(p+q.id))].filter(Boolean).join(' · ')||'No notes yet — revisit this step to add your idea.')}</div>`}).join('');
 if(s.type==='present')html+='<p class="notice">Keep your photographs and sketches together. Use “Download my project notes” to save your written reflections. Photo uploads and a presentation gallery will be added later.</p>';
 if(s.type==='next'){const next=course.lessons[l.number];const allDone=course.lessons.every(x=>state.completed.includes(x.lessonId));html+=next?`<h3>${next.title}</h3><p>${next.number===2?'How did medieval builders use structure to reach higher?':next.question}</p><button class="btn" data-complete="${l.number}">Complete lesson & continue to Lesson ${next.number}</button>`:`<p>${allDone?'You have completed all six lessons. Your material has a new story.':'Mark this lesson complete when you have presented your project. Complete all six lessons to finish the course.'}</p><button class="btn" data-complete="${l.number}">Complete Lesson 6</button>`;}
 return html;
}
function lesson(n,id){const l=course.lessons[n-1];let idx=l.screens.findIndex(s=>s.screenId===id);if(idx<0)idx=0;const s=l.screens[idx];if(!state.started.includes(l.lessonId))state.started.push(l.lessonId);state.positions[n]=s.screenId;save();document.title=`${l.title} · RE:MAKE 01`;
 main.innerHTML=`<a href="#overview">← Course overview</a><header class="lesson-head"><div class="eyebrow">RE:MAKE 01 / LESSON ${n} OF 6</div><h1>${l.title}</h1><progress value="${idx+1}" max="${l.screens.length}" aria-label="Lesson section ${idx+1} of ${l.screens.length}"></progress><p class="muted">Section ${idx+1} of ${l.screens.length}${s.estimatedTime||l.estimatedTime?" · "+esc(s.estimatedTime||l.estimatedTime):""}</p></header><div class="layout"><nav class="steps" aria-label="Lesson sections">${l.screens.map((x,i)=>`<a href="${route(n,x.screenId)}" ${i===idx?'aria-current="step"':''}>${i+1}. ${esc(x.title)}</a>`).join('')}</nav><section class="stage"><h2>${s.type==='next'&&n===6&&!course.lessons.every(x=>state.completed.includes(x.lessonId))?'READY TO PRESENT?':esc(s.title)}</h2><p>${esc(s.instruction)}</p>${content(s,l)}<div class="navigation">${idx?link(route(n,l.screens[idx-1].screenId),'← Previous',true):link(n===1?'#prepare':'#overview',n===1?'Materials':'Overview',true)}${idx<l.screens.length-1?link(route(n,l.screens[idx+1].screenId),'Next: '+l.screens[idx+1].title+' →'):link('#overview','Course overview',true)}</div></section></div>`;
}
function render(){const parts=location.hash.slice(1).split('/');document.body.classList.toggle('gothic-flow',parts[0]==='project'&&parts[1]==='gothic');document.body.classList.toggle('course-entry',!['project','lesson','prepare'].includes(parts[0]));document.title=course.title+' · FEI TeamArt';if(parts[0]==='project'&&parts[1]==='gothic')gothic.render(parts);else if(parts[0]==='prepare')prepare();else if(parts[0]==='lesson'&&/^[1-6]$/.test(parts[1]))lesson(Number(parts[1]),parts[2]);else overview();main.focus({preventScroll:true});window.scrollTo(0,0);}
main.addEventListener('input',e=>{const el=e.target;if(!el.dataset.response)return;state.responses[el.dataset.response]=el.type==='checkbox'?el.checked:el.value;el.closest('.tool-card')?.classList.toggle('is-ready',el.checked);save();});
main.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.choice){const id=b.dataset.choice;let values=Array.isArray(response(id))?[...response(id)]:[];values=values.includes(b.dataset.value)?values.filter(v=>v!==b.dataset.value):b.dataset.single==='true'?[b.dataset.value]:[...values,b.dataset.value];state.responses[id]=values;main.querySelectorAll('[data-choice]').forEach(x=>{if(x.dataset.choice===id)x.setAttribute('aria-pressed',values.includes(x.dataset.value))});save();}if(b.dataset.toggle){const id=b.dataset.toggle;state.responses[id]=!response(id);b.setAttribute('aria-pressed',state.responses[id]);b.textContent=state.responses[id]?'Trying it ✓':'Try It';save();}if(b.dataset.complete){const n=Number(b.dataset.complete),l=course.lessons[n-1];if(!state.completed.includes(l.lessonId))state.completed.push(l.lessonId);save();if(n<6)location.hash=route(n+1);else{render();status.textContent=course.lessons.every(x=>state.completed.includes(x.lessonId))?'Project complete · all six lessons finished.':'Lesson 6 complete · revisit the overview to finish remaining lessons.';}}});
document.querySelector('#export').onclick=()=>{const blob=new Blob([JSON.stringify({course:course.title,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='remake-cardboard-project-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
document.querySelector('.skip').addEventListener('click', e => { e.preventDefault(); main.focus(); });
const gothic = createGothicProject({main,state,save,esc,link,materialBoard});
main.addEventListener('click',gothic.handleClick);
window.addEventListener('hashchange',render);render();
