import {gothicProject as P} from './gothic-data.js';
export function createGothicProject({main,state,save,esc,link,materialBoard}){
 const path=(id='',step='')=>'#project/gothic'+(id?'/'+id:'')+(step?'/'+step:'');
 const done=()=>Array.isArray(state.responses['gothic:done'])?state.responses['gothic:done']:[];
 const completed=e=>e.steps.length>0&&(e.mode==='choices'?e.steps.some(s=>done().includes(e.id+':'+s.screenId)):e.steps.every(s=>done().includes(e.id+':'+s.screenId)));
 let cropId=0;
 const picture=(src,width,height,rect,label,cls='')=>{const id='gothic-crop-'+(++cropId);return `<svg class="guide-crop ${cls}" viewBox="${rect.join(' ')}" role="img" aria-label="${esc(label)}"><defs><clipPath id="${id}"><rect x="${rect[0]}" y="${rect[1]}" width="${rect[2]}" height="${rect[3]}" /></clipPath></defs><image href="${src}" width="${width}" height="${height}" clip-path="url(#${id})" /></svg>`;};
 const mapPic=(e)=>picture(P.map.src,P.map.width,P.map.height,e.mapRect,e.title);
 const resume=e=>e.mode==='choices'?path(e.id):path(e.id,state.responses['gothic:position:'+e.id]||e.steps[0].screenId);
 function render(parts){
  document.title='Gothic cardboard project · FEI TeamArt';
  const id=parts[2],e=P.elements.find(x=>x.id===id);
  if(id==='materials'){main.innerHTML=`${link(path(),'← Project map',true)}<header class="prepare-heading"><div class="eyebrow">Today’s build</div><h1>Get ready to build</h1></header>${materialBoard()}<div class="ready-bar"><span>Cardboard · pencil · ruler · scissors · glue</span>${link(resume(P.elements[0]),'Start the pointed arch →')}</div>`;return;}
  if(!e){map();return;}
  if(!e.steps.length){main.innerHTML=`${link(path(),'← Project map',true)}<div class="project-intro"><div><div class="eyebrow">Coming next</div><h1>${e.title}</h1><p>Your teacher will add the step pictures and demo here.</p>${link(path(),'Back to today’s three elements')}</div>${mapPic(e)}</div>`;return;}
  if(parts[3]==='finished'){finish(e);return;}
  if(e.mode==='choices'&&!e.steps.some(s=>s.screenId===parts[3])){choices(e);return;}
  const index=Math.max(0,e.steps.findIndex(s=>s.screenId===parts[3])),s=e.steps[index];
  state.responses['gothic:position:'+e.id]=s.screenId;save();
  main.innerHTML=`<div class="project-top">${link(path(),'← Project map',true)}<span>${e.title} · ${e.mode==='choices'?'Option ':''}${index+1} / ${e.steps.length}</span></div>
  <nav class="build-step-nav" aria-label="Making steps">${e.steps.map((x,i)=>`<a href="${path(e.id,x.screenId)}" aria-label="${e.mode==='choices'?'Option':'Step'} ${i+1}: ${esc(x.title)}" ${i===index?'aria-current="step"':''}>${done().includes(e.id+':'+x.screenId)?'✓':i+1}</a>`).join('')}</nav>
  <div class="making-stage"><div class="making-visual">${picture(e.sheet,e.width,e.height,s.rect,s.title+' — '+s.instruction)}<button class="text-button" data-gothic-zoom>Enlarge picture ↗</button></div><div class="making-action"><div class="eyebrow">${s.part||e.title} / ${e.mode==='choices'?'Option':'Step'} ${index+1}</div><h1>${s.title}</h1><p class="one-action">${s.instruction}</p>${s.cutting?'<p class="safety">Ask an adult for inner cuts or craft-knife work.</p>':''}<div class="build-video">${s.video.src?`<video controls preload="metadata" ${s.video.poster?`poster="${esc(s.video.poster)}"`:''} src="${esc(s.video.src)}" aria-label="${esc(s.title)} teacher demo">${s.video.captions?`<track kind="captions" src="${esc(s.video.captions)}" srclang="en" label="English" default>`:''}</video>${s.video.transcript?`<details><summary>Read the demo</summary><p>${esc(s.video.transcript)}</p></details>`:''}`:'<span aria-hidden="true">▷</span> Teacher demo · coming soon'}</div><button class="btn" data-gothic-done="${e.id}:${s.screenId}">${e.mode==='choices'?'I made this detail ✓':index===e.steps.length-1?(e.id==='build'?'Finish the build ✓':'Finish this section ✓'):'Done · next step →'}</button><div class="build-secondary">${e.mode==='choices'?link(path(e.id),'← Choose a different detail',true):index?link(path(e.id,e.steps[index-1].screenId),'← Back',true):link(path(),'← Choose element',true)}${e.mode!=='choices'&&index<e.steps.length-1?link(path(e.id,e.steps[index+1].screenId),'Preview next →',true):''}</div><details class="quiet-details"><summary>See the full guide</summary><a href="${e.sheet}" target="_blank" rel="noopener"><img class="full-guide" src="${e.sheet}" alt="Complete ${e.title} process sheet" loading="lazy"></a></details></div></div>
  <dialog class="picture-dialog" aria-label="Enlarged step picture"><button class="btn secondary" data-gothic-close>Close ×</button>${picture(e.sheet,e.width,e.height,s.rect,s.title+' — '+s.instruction)}</dialog>`;
 }
 function map(){main.innerHTML=`${link('#overview','← Cardboard course',true)}<header class="project-intro"><div><div class="eyebrow">Today’s example project</div><h1>${P.title}</h1><p>Make the parts.<br>Then bring your own building together.</p><div class="actions">${link(resume(P.elements[0]),'Start / continue building →')}${link(path('materials'),'Prepare materials',true)}</div></div>${picture(P.map.src,P.map.width,P.map.height,[868,880,274,288],'Example of a finished Gothic-inspired cardboard cathedral')}</header><div class="project-phase"><b>01 · Make the elements</b><span>02 · Combine</span><span>03 · Build</span></div><h2 class="project-section-title">Make your building elements</h2><div class="element-grid">${P.elements.slice(0,5).map((e,i)=>`<a class="element-card" href="${resume(e)}">${mapPic(e)}<span class="eyebrow">ELEMENT 0${i+1} · ${completed(e)?'Complete':e.mode==='choices'?'Choose one':e.steps.filter(s=>done().includes(e.id+':'+s.screenId)).length+' / '+e.steps.length}</span><h3>${e.title} <span>→</span></h3></a>`).join('')}</div><details class="photo-reference"><summary>See the whole project map</summary><a href="${P.map.src}" target="_blank" rel="noopener"><img class="full-guide" src="${P.map.src}" alt="Whole project: five Gothic elements, combine them, then build your cathedral" loading="lazy"></a></details><h2 class="project-section-title">Bring the pieces together</h2><div class="element-grid upcoming">${P.elements.slice(5).map(e=>`<a class="element-card" href="${resume(e)}">${mapPic(e)}<h3>${e.title}</h3><span class="muted">${completed(e)?'Complete':e.steps.length+' visual steps →'}</span></a>`).join('')}</div><p class="muted">A Gothic-inspired example. Change the shapes and arrangement to make it yours.</p>`;}
 function choices(e){main.innerHTML=`${link(path(),'← Project map',true)}<header class="prepare-heading"><div class="eyebrow">Element 05 · Choose one or more</div><h1>Small details. Your choice.</h1><p>Pick a detail to make. You don’t need all five.</p></header><div class="element-grid">${e.steps.map(s=>`<a class="element-card" href="${path(e.id,s.screenId)}">${picture(e.sheet,e.width,e.height,s.rect,s.title)}<h3>${s.title}</h3><span class="muted">${done().includes(e.id+':'+s.screenId)?'Made ✓':'Choose this detail →'}</span></a>`).join('')}</div><div class="actions">${link(path('combine','plan'),'Skip decoration · plan the building →',true)}</div><details class="photo-reference"><summary>See all detail ideas</summary><img class="full-guide" src="${e.sheet}" alt="Five decorative options and examples on a building"></details>`;}
 function finish(e){const next=P.elements[P.elements.indexOf(e)+1],isBuild=e.id==='build';main.innerHTML=`${link(path(),'← Project map',true)}<div class="project-intro"><div><div class="eyebrow">${completed(e)?(isBuild?'Build complete':'Section complete'):'Section preview'}</div><h1>${isBuild?'Your Gothic building':e.title}</h1><p>${isBuild?'One material. Your own design.':'Keep your pieces together for assembly.'}</p>${completed(e)?'':'<p class="muted">Some steps are still unchecked. Revisit them when you’re ready.</p>'}<div class="actions">${next?.steps.length?link(resume(next),'Next: '+next.title+' →'):link('#lesson/6/document','Photograph + present →')}${link(resume(e),e.mode==='choices'?'Choose another detail':'Revisit steps',true)}</div></div>${picture(e.sheet,e.width,e.height,e.resultRect,e.title+' finished example')}</div>`;}
 function handleClick(event){const b=event.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-gothic-zoom'))main.querySelector('dialog').showModal();
  if(b.hasAttribute('data-gothic-close'))main.querySelector('dialog').close();
  if(b.dataset.gothicDone){const [id,stepId]=b.dataset.gothicDone.split(':'),e=P.elements.find(x=>x.id===id);if(!e)return;const i=e.steps.findIndex(x=>x.screenId===stepId);if(i<0)return;state.responses['gothic:done']=[...new Set([...done(),b.dataset.gothicDone])];save();location.hash=path(id,e.mode==='choices'?'finished':e.steps[i+1]?.screenId||'finished');}
 }
 return {render,handleClick};
}
