import {gothicProject as P} from './gothic-data.js';
export function createGothicProject({main,state,save,esc,link,materialBoard}){
 const path=(id='',step='')=>'#project/gothic'+(id?'/'+id:'')+(step?'/'+step:'');
 const done=()=>Array.isArray(state.responses['gothic:done'])?state.responses['gothic:done']:[];
 const completed=e=>e.steps.length>0&&(e.mode==='choices'?e.steps.some(s=>done().includes(e.id+':'+s.screenId)):e.steps.every(s=>done().includes(e.id+':'+s.screenId)));
 let cropId=0;
 const picture=(src,width,height,rect,label,cls='')=>{const id='gothic-crop-'+(++cropId);return `<svg class="guide-crop ${cls}" viewBox="${rect.join(' ')}" role="img" aria-label="${esc(label)}"><defs><clipPath id="${id}"><rect x="${rect[0]}" y="${rect[1]}" width="${rect[2]}" height="${rect[3]}" /></clipPath></defs><image href="${src}" width="${width}" height="${height}" clip-path="url(#${id})" /></svg>`;};
 const mapPic=(e)=>picture(P.map.src,P.map.width,P.map.height,e.mapRect,e.title);
 const skipped=e=>e.mode==='choices'&&state.responses['gothic:skip-decoration']===true;
 const resume=e=>e.mode==='choices'?path(e.id):path(e.id,(e.steps.find(s=>!done().includes(e.id+':'+s.screenId))||e.steps[0]).screenId);
 const nextElement=()=>P.elements.find(e=>!completed(e)&&!skipped(e));
 function render(parts){
  document.title='Gothic cardboard project · FEI TeamArt';
  const id=parts[2],e=P.elements.find(x=>x.id===id);
  if(id==='intro'){main.innerHTML=`<div class="project-top">${link(path(),'← Learning path',true)}<span>RE:MAKE · CARDBOARD</span></div><div class="project-intro"><div><div class="eyebrow">Your next creation</div><h1>One box.<br>A whole new building.</h1><p>Make five Gothic elements. Plan your design. Bring it all together.</p>${link(path('materials'),'Get ready →')}</div>${picture(P.map.src,P.map.width,P.map.height,[868,880,274,288],'A Gothic-inspired cardboard building')}</div>`;return;}
  if(id==='materials'){const tools=parts[3]==='tools';main.innerHTML=`<div class="project-top">${link(path(),'← Learning path',true)}<span>Get ready · ${tools?'2':'1'} / 2</span></div><div class="focused-preparation">${materialBoard(tools?'tools':'cardboard')}</div><div class="flow-actions">${link(tools?path('materials'):path('intro'),'← Back',true)}${tools?'<button class="btn" data-gothic-ready>I’m ready · start building →</button>':link(path('materials','tools'),'Next · tools →')}</div>`;return;}
  if(!e){map();return;}
  if(!e.steps.length){main.innerHTML=`${link(path(),'← Learning path',true)}<div class="project-intro"><div><div class="eyebrow">Coming next</div><h1>${e.title}</h1><p>Your teacher will add the step pictures and demo here.</p>${link(path(),'Back to today’s three elements')}</div>${mapPic(e)}</div>`;return;}
  if(parts[3]==='finished'){finish(e);return;}
  if(e.mode==='choices'&&!e.steps.some(s=>s.screenId===parts[3])){choices(e);return;}
  const index=Math.max(0,e.steps.findIndex(s=>s.screenId===parts[3])),s=e.steps[index];
  state.responses['gothic:position:'+e.id]=s.screenId;save();
  main.innerHTML=`<div class="project-top">${link(path(),'← Learning path',true)}<span>${e.title} · ${e.mode==='choices'?'Option ':''}${index+1} / ${e.steps.length}</span></div>
  <progress class="making-progress" value="${index+1}" max="${e.steps.length}" aria-label="${e.mode==='choices'?'Detail':'Step'} ${index+1} of ${e.steps.length}"></progress>
  <div class="making-stage"><div class="making-visual">${picture(e.sheet,e.width,e.height,s.rect,s.title+' — '+s.instruction)}<button class="text-button" data-gothic-zoom>Enlarge picture ↗</button></div><div class="making-action"><div class="eyebrow">${s.part||e.title} / ${e.mode==='choices'?'Option':'Step'} ${index+1}</div><h1>${s.title}</h1><p class="one-action">${s.instruction}</p>${s.cutting?'<p class="safety">Ask an adult for inner cuts or craft-knife work.</p>':''}<div class="build-video">${s.video.src?`<video controls preload="metadata" ${s.video.poster?`poster="${esc(s.video.poster)}"`:''} src="${esc(s.video.src)}" aria-label="${esc(s.title)} teacher demo">${s.video.captions?`<track kind="captions" src="${esc(s.video.captions)}" srclang="en" label="English" default>`:''}</video>${s.video.transcript?`<details><summary>Read the demo</summary><p>${esc(s.video.transcript)}</p></details>`:''}`:''}</div></div></div><div class="flow-actions">${e.mode==='choices'?link(path(e.id),'← Details',true):index?link(path(e.id,e.steps[index-1].screenId),'← Back',true):link(path(),'← Learning path',true)}<button class="btn" data-gothic-done="${e.id}:${s.screenId}">${e.mode==='choices'?'I made this detail ✓':index===e.steps.length-1?(e.id==='build'?'Finish the build ✓':'Finish this section ✓'):'Done · next step →'}</button></div>

  <dialog class="picture-dialog" aria-label="Enlarged step picture"><button class="btn secondary" data-gothic-close>Close ×</button>${picture(e.sheet,e.width,e.height,s.rect,s.title+' — '+s.instruction)}</dialog>`;
 }
 function map(){const next=nextElement(),started=done().length>0,ready=state.responses['gothic:ready']||started;main.innerHTML=`<div class="project-top">${link('#overview','← Cardboard',true)}<span>SMART CLASS</span></div><header class="path-heading"><div class="eyebrow">Your learning path</div><h1>Build a Gothic-inspired Cathedral</h1><p>Make the parts. Plan. Build your own.</p><div class="path-progress">${P.elements.filter(completed).length} / 7 sections complete</div></header><ol class="learning-path">${P.elements.map((e,i)=>`<li><a href="${resume(e)}"><span class="route-number">${completed(e)?'✓':i+1}</span>${mapPic(e)}<span><strong>${e.title}</strong><small>${completed(e)?'Complete · revisit':skipped(e)?'Skipped · optional':e.mode==='choices'?'Choose one detail · optional':e.steps.length+' picture steps'}</small></span><span aria-hidden="true">→</span></a></li>`).join('')}</ol><div class="path-start">${link(next?(ready?resume(next):path('intro')):path('build','finished'),next?(started?'Continue learning →':'Start learning →'):'View your finished build →')}</div><details class="quiet-details path-resources"><summary>Materials & reference sheets</summary><p>${link(path('materials'),'Prepare materials',true)}</p><a href="${P.map.src}" target="_blank" rel="noopener">Whole project map ↗</a>${P.elements.filter((e,i,all)=>all.findIndex(x=>x.sheet===e.sheet)===i).map(e=>`<p><a href="${e.sheet}" target="_blank" rel="noopener">${e.title} guide ↗</a></p>`).join('')}</details>`;}
 function choices(e){main.innerHTML=`${link(path(),'← Learning path',true)}<header class="prepare-heading"><div class="eyebrow">Element 05 · Choose one or more</div><h1>Small details. Your choice.</h1><p>Pick a detail to make. You don’t need all five.</p></header><div class="element-grid">${e.steps.map(s=>`<a class="element-card" href="${path(e.id,s.screenId)}">${picture(e.sheet,e.width,e.height,s.rect,s.title)}<h3>${s.title}</h3><span class="muted">${done().includes(e.id+':'+s.screenId)?'Made ✓':'Choose this detail →'}</span></a>`).join('')}</div><div class="actions"><button class="btn secondary" data-gothic-skip>Skip decoration · continue →</button></div><details class="photo-reference"><summary>See all detail ideas</summary><img class="full-guide" src="${e.sheet}" alt="Five decorative options and examples on a building"></details>`;}
 function finish(e){const next=P.elements[P.elements.indexOf(e)+1],isBuild=e.id==='build';main.innerHTML=`${link(path(),'← Learning path',true)}<div class="project-intro"><div><div class="eyebrow">${completed(e)?(isBuild?'Build complete':'Section complete'):'Section preview'}</div><h1>${isBuild?'Your Gothic building':e.title}</h1><p>${isBuild?'One material. Your own design.':'Keep your pieces together for assembly.'}</p>${completed(e)?'':'<p class="muted">Some steps are still unchecked. Revisit them when you’re ready.</p>'}<div class="actions">${next?.steps.length?link(resume(next),'Next: '+next.title+' →'):link('#lesson/6/document','Photograph + present →')}${link(resume(e),e.mode==='choices'?'Choose another detail':'Revisit steps',true)}</div></div>${picture(e.sheet,e.width,e.height,e.resultRect,e.title+' finished example')}</div>`;}
 function handleClick(event){const b=event.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-gothic-ready')){state.responses['gothic:ready']=true;save();location.hash=resume(nextElement()||P.elements[0]);}
  if(b.hasAttribute('data-gothic-skip')){state.responses['gothic:skip-decoration']=true;save();location.hash=resume(P.elements[5]);}
  if(b.hasAttribute('data-gothic-zoom'))main.querySelector('dialog').showModal();
  if(b.hasAttribute('data-gothic-close'))main.querySelector('dialog').close();
  if(b.dataset.gothicDone){const [id,stepId]=b.dataset.gothicDone.split(':'),e=P.elements.find(x=>x.id===id);if(!e)return;const i=e.steps.findIndex(x=>x.screenId===stepId);if(i<0)return;state.responses['gothic:done']=[...new Set([...done(),b.dataset.gothicDone])];save();location.hash=path(id,e.mode==='choices'?'finished':e.steps[i+1]?.screenId||'finished');}
 }
 return {render,handleClick};
}
