(() => {
  'use strict';
  const D = window.COLOR_LAB;
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const stage = $('#stage');
  const saved = JSON.parse(localStorage.getItem('fei_color_lab_01') || '{}');
  const paintboxVersion = 4;
  const baseCakes = [{color:'#dc493a',name:'Red',family:'Original'},{color:'#e6b633',name:'Yellow',family:'Original'},{color:'#315e9f',name:'Blue',family:'Original'},{color:'#292726',name:'Black',family:'Original'},{color:'#f9f6ed',name:'White',family:'Original'}];
  const currentMixNames=new Map(Object.values(D.mixes).flatMap(m=>m.colors.slice(1).map((color,i)=>[color,m.names[i+1]])));
  const migratedSwatches=(saved.swatches||[]).filter(s=>!baseCakes.some(b=>b.name===s.name)).map(s=>currentMixNames.has(s.color)?{...s,name:currentMixNames.get(s.color)}:s);
  const state = { index: Math.min(saved.index || 0, D.stages.length - 1), swatches:saved.paintboxVersion>=2?migratedSwatches:[], rounds:saved.rounds||{}, sound:false };

  function persist(){ localStorage.setItem('fei_color_lab_01', JSON.stringify({index:state.index,swatches:state.swatches,rounds:state.rounds,paintboxVersion})); }
  function allCakes(){return [...baseCakes,...state.swatches]}
  function cakeWells(total=30){const cakes=allCakes();return Array.from({length:total},(_,i)=>cakes[i]?`<i class="filled ${i<5?'original-cake':'mixed-cake'}" style="--c:${cakes[i].color}" title="${cakes[i].name}"><span>${i<5?'ORIGINAL':'MIXED'}</span></i>`:'<i></i>').join('')}
  function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>t.classList.remove('show'),1800); }
  function classroomDemo(){ return `<section class="classroom-demo" aria-labelledby="classroom-demo-title"><div class="classroom-video"><div class="classroom-video-frame"><iframe src="https://customer-a78os4oj56dr67ab.cloudflarestream.com/39e25c9c61d6e990a6e16828ea50f561/iframe?poster=https%3A%2F%2Fcustomer-a78os4oj56dr67ab.cloudflarestream.com%2F39e25c9c61d6e990a6e16828ea50f561%2Fthumbnails%2Fthumbnail.jpg%3Ftime%3D%26height%3D600" title="Real Color Practice classroom demonstration" loading="lazy" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div><p class="classroom-controls">Press play when you’re ready. Use the speaker control to listen, or watch silently.</p></div><div class="classroom-copy"><div class="eyebrow">REAL CLASSROOM REFERENCE</div><h3 id="classroom-demo-title">See how the mixing happens on paper.</h3><p>This was recorded during a real Zoom class as the teacher guided students through the same color-mixing process.</p><p class="recording-note">It is not a polished studio video: the picture is soft, and the AI-translated voice may sound a little robotic. The hands-on demonstration itself is real.</p><p><b>Watch for:</b> controlling water, changing paint proportions, mixing thoroughly, and placing each new color on paper.</p></div></section>`; }
  function button(label='Continue', extra=''){ return `<button class="btn" data-next ${extra}>${label}</button>`; }
  function shell(kicker,title,body,cls=''){ return `<section class="scene ${cls}"><div class="eyebrow">${kicker}</div><h2>${title}</h2>${body}</section>`; }
  function whyStory(){
    const poster='https://customer-a78os4oj56dr67ab.cloudflarestream.com/39e25c9c61d6e990a6e16828ea50f561/thumbnails/thumbnail.jpg?time=&height=600';
    const paletteColors=['#dc493a','#e6b633','#315e9f','#292726','#f9f6ed','#e39a31','#dd762f','#d95834','#a44667','#754982','#514f91','#327d78','#47935b','#91a842','#795844','#f3df93','#efa0a1','#9eb8d9','#bba8cf','#add2b5'];
    return `<div class="story-card" id="story">
      <div class="story-slide story-cover"><div class="story-photo cover-photo"><img src="assets/materials-reference.png" alt="Real paints, palette, brush, water, and cloth ready for Color Practice"><span class="story-wash"></span><svg class="story-ink" viewBox="0 0 100 62" aria-hidden="true"><path d="M17 44 C31 54 56 52 72 40"/><path d="M67 36 L74 40 L68 46"/></svg><b class="story-sticker">REAL PAINT<br>REAL DISCOVERY</b></div><div class="story-copy"><h3>Why learn color with real paint?</h3><p>Follow the moving marks. See what your hands will discover.</p><button class="btn" data-story-play>Play 40-second introduction</button></div></div>
      <div class="story-slide"><div class="story-photo"><img src="assets/materials-reference.png" alt="Teacher's real color-mixing materials"><span class="photo-focus focus-paints">START WITH 5</span><span class="photo-focus focus-palette">MIX HERE</span><svg class="story-ink" viewBox="0 0 100 62" aria-hidden="true"><path d="M38 39 C48 28 57 28 67 37"/><circle cx="55" cy="31" r="18"/></svg></div><div class="story-copy"><h3>A small set can make a large world.</h3><p>Red, yellow, blue, black, and white are starting points—not limits.</p></div></div>
      <div class="story-slide"><div class="story-photo classroom-still"><img src="${poster}" alt="Still from the real Zoom classroom color-mixing demonstration"><span class="story-video-mark">REAL CLASSROOM</span><span class="story-play-ring">▶</span><svg class="story-ink" viewBox="0 0 100 62" aria-hidden="true"><path d="M14 49 C31 42 48 49 63 38 C72 32 77 24 87 21"/></svg></div><div class="story-copy"><h3>Watch color change in real time.</h3><p>Water, pressure, and pigment proportions all change what appears on the paper.</p></div></div>
      <div class="story-slide"><div class="story-interface"><div class="mini-top"><i></i><i></i><i></i><b>MIX 1 OF 3 · YELLOW → RED</b></div><div class="mini-recipe"><span>8 parts Yellow</span><b>+</b><span>1 part Red</span></div><div class="mini-palette"><i class="mini-yellow"></i><i class="mini-red"></i><i class="mini-orange"></i><svg viewBox="0 0 100 50" aria-hidden="true"><path d="M28 28 C43 7 62 44 77 20"/></svg><strong>☝️ MIX</strong></div><div class="mini-paper">${['#e6b633','#e39a31','#dd762f','#d95834','#d45137'].map((c,i)=>`<i style="--c:${c};--d:${i*.12}s"></i>`).join('')}</div></div><div class="story-copy"><h3>Small changes train your eye.</h3><p>Mix one proportion, paint it on paper, then compare it with the color before.</p></div></div>
      <div class="story-slide"><div class="story-paintbox"><div class="story-box-lid">MY HAND-MIXED COLORS</div><div class="story-cakes">${paletteColors.map((c,i)=>`<i style="--c:${c};--d:${i*.035}s"></i>`).join('')}</div><svg class="story-ink" viewBox="0 0 100 62" aria-hidden="true"><path d="M9 51 C26 57 71 57 90 46"/><path d="M85 42 L92 46 L86 52"/></svg><b class="palette-count">5 paints → 20+ colors</b></div><div class="story-copy"><h3>Lesson 01: build your own palette.</h3><p>Mix on screen, test on paper, and save every new color you create.</p></div></div>
      <button class="story-skip" data-story-skip>Skip</button><div class="story-progress"></div>
    </div>`;
  }
  function next(){ if(state.index < D.stages.length-1){ state.index++; persist(); render(); } }
  function prev(){ if(state.index>0){ state.index--; render(); } }
  function rail(){ $('#paint-trail').innerHTML=D.stages.map((x,i)=>`<button class="trail-dot ${i<state.index?'done':''} ${i===state.index?'current':''}" style="--r:${(i%4-2)*8}deg" aria-label="${x.label}${i===state.index?', current step':''}" ${i>state.index?'disabled':''} data-jump="${i}"></button>`).join(''); }
  function wireCommon(){ $('[data-next]')?.addEventListener('click',next); $$('[data-jump]').forEach(b=>b.addEventListener('click',()=>{state.index=+b.dataset.jump;render()})); stage.focus({preventScroll:true}); }

  function opening(){
    const complete=localStorage.getItem('fei_color_lab_01_complete');
    const showMap=()=>{stage.innerHTML=`<section class="scene course-map-scene"><div class="eyebrow">Skill · Color Practice</div><h1>Your color journey</h1><p class="lead">See where you are. Build a palette that grows with every lesson.</p><div class="course-map"><button class="map-stop available" data-open-why><span class="map-dot tricolor"></span><b>Why Color?</b><small>Start here · 40 sec</small></button><span class="map-line ${complete?'done':''}"></span><button class="map-stop ${complete?'done':'current'}" data-open-lesson><span class="map-dot primary-dot"></span><b>01 · Primary Colors</b><small>${complete?'✓ Complete':'Build your first palette'}</small></button><span class="map-line"></span><button class="map-stop locked" disabled><span class="map-dot analogous-dot"></span><b>02 · Color Neighbors</b><small>Coming soon</small></button><span class="map-line"></span><button class="map-stop locked" disabled><span class="map-dot complement-dot"></span><b>03 · Complementary Colors</b><small>Coming soon</small></button><span class="map-line"></span><button class="map-stop locked" disabled><span class="map-dot warm-dot"></span><b>04 · Warm & Cool</b><small>Coming soon</small></button></div><div class="palette-preview"><span>Your paint box</span><div>${allCakes().slice(0,14).map((s,i)=>`<i class="${i<5?'original-cake':''}" style="--c:${s.color}" title="${s.name}${i<5?' · Original paint':''}"></i>`).join('')}</div></div></section>`;$('[data-open-why]').onclick=showWhy;$('[data-open-lesson]').onclick=showWhy;};
    const showWhy=()=>{stage.innerHTML=`<section class="scene why-scene"><button class="map-back" data-map>← Course map</button><div class="eyebrow">Color Practice · Why Color?</div><h1>Color begins with mixing.</h1><p class="lead">A 40-second visual introduction</p>${whyStory()}<div class="actions">${button('Prepare my studio','disabled')}</div></section>`;const story=$('#story'),nextBtn=$('[data-next]'),slides=[...story.querySelectorAll('.story-slide')];slides.forEach((slide,i)=>slide.style.setProperty('--scene',`${i*8}s`));let timer=null;const finish=()=>{clearTimeout(timer);story.classList.remove('playing');slides.forEach(x=>x.style.display='none');slides.at(-1).style.cssText='display:grid;opacity:1;transform:none;pointer-events:auto';nextBtn.disabled=false;nextBtn.focus();toast('Ready to build your palette.')};$('[data-story-play]').onclick=()=>{story.classList.add('playing');timer=setTimeout(finish,40000)};$('[data-story-skip]').onclick=finish;$('[data-map]').onclick=showMap;nextBtn.onclick=next;};
    showMap();
  }
  function prepare(){
    stage.innerHTML=shell('Prepare your studio','Match these materials at home.',`<figure class="materials-reference"><img src="assets/materials-reference.png" alt="A real color-mixing workspace with a metal palette, five paint tubes, a brush in a water cup, and a cloth"><figcaption><b>Teacher’s real setup</b><span>Use this table as your visual guide. Your brands and containers can look different.</span></figcaption></figure><p class="lead">Now tap each material when it’s beside you.</p><div class="materials">${D.materials.map((m,i)=>`<button class="material" data-mat="${i}"><span class="material-photo" style="--mx:${i%5};--my:${Math.floor(i/5)}" role="img" aria-label="Photo of ${m[1]}"></span><span>${m[1]}</span></button>`).join('')}</div><p class="lead" style="margin-top:18px">Gouache recommended. Watercolor also works.</p><div class="actions"><button class="btn" data-ready disabled>I have everything</button></div>`,'wide');
    const done=new Set(); $$('[data-mat]').forEach(b=>b.onclick=()=>{ b.classList.toggle('ready'); b.classList.contains('ready')?done.add(b.dataset.mat):done.delete(b.dataset.mat); $('[data-ready]').disabled=done.size<D.materials.length; }); $('[data-ready]').onclick=next;
  }
  function primaries(){
    stage.innerHTML=shell('What are primary colors?','Meet Red, Yellow, and Blue.',`<p class="lead">These are traditional painting primaries—our starting colors.</p><p class="instruction" id="tri-prompt">Drag or tap each color onto the triangle.</p><div class="blob-tray">${[['#dc493a','Red'],['#e6b633','Yellow'],['#315e9f','Blue']].map((c,i)=>`<button class="paint-blob" draggable="true" data-primary="${i}" style="--c:${c[0]}">${c[1]}</button>`).join('')}</div><div class="triangle"><div class="drop" data-i="0">1</div><div class="drop" data-i="1">2</div><div class="drop" data-i="2">3</div><i class="tri-line"></i></div><details><summary>Why these three?</summary><p>They are a practical starting set for learning how paint mixtures relate. They do not literally make every possible pigment.</p></details><div class="challenge-card"><b>Today’s challenge</b><span>Start with only three colors. Notice how every small change in proportion creates a new relationship.</span></div><div class="actions">${button('Build colors from these three','disabled')}</div>`);
    let count=0, selected=null; const place=(blob,drop)=>{ if(blob.dataset.placed)return; blob.dataset.placed='1'; blob.style.position='static'; drop.textContent=''; drop.append(blob); count++; $('#tri-prompt').textContent=count===3?'These are our starting colors.':'Choose another color.'; if(count===3){$('[data-next]').disabled=false;toast('Three colors. So many possibilities.')} };
    $$('[data-primary]').forEach(b=>{b.onclick=()=>{if(selected){selected.classList.remove('selected')} selected=b;b.style.outline='3px solid #292622'};b.ondragstart=e=>e.dataTransfer.setData('text',b.dataset.primary)}); $$('.drop').forEach(d=>{d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();place($(`[data-primary="${e.dataTransfer.getData('text')}"]`),d)};d.onclick=()=>{if(selected){place(selected,d);selected=null}}});
  }
  function addSaved(color,name,family){ const old=state.swatches.findIndex(s=>s.name===name||s.color===color);if(old>=0){state.swatches[old]={color,name,family};persist();return {added:false,index:old}}state.swatches.push({color,name,family});persist();return {added:true,index:state.swatches.length-1}; }
  function refreshPaintbox(){const cakes=allCakes(),wells=$$('.paintbox-wells i');wells.forEach((w,i)=>{const s=cakes[i];w.classList.toggle('filled',!!s);w.classList.toggle('original-cake',i<5&&!!s);w.classList.toggle('mixed-cake',i>=5&&!!s);if(s){w.style.setProperty('--c',s.color);w.title=s.name}})}
  function flyToPaintbox(color,source,index){const target=$$('.paintbox-wells i')[index+5];if(!target){refreshPaintbox();return}const a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),sx=Math.max(24,Math.min(innerWidth-64,a.left+a.width/2)),sy=Math.max(20,Math.min(innerHeight-52,a.top+a.height/2)),tx=b.left+b.width/2,ty=b.top+b.height/2,chip=document.createElement('i');chip.className='flying-paint-cake';chip.style.cssText=`--c:${color};left:${sx-20}px;top:${sy-16}px`;document.body.append(chip);requestAnimationFrame(()=>{chip.style.transform=`translate(${tx-sx}px,${ty-sy}px) scale(.62) rotate(8deg)`;chip.style.opacity='.72'});setTimeout(()=>{target.style.setProperty('--c',color);target.classList.add('filled','mixed-cake','just-filled');chip.remove();setTimeout(()=>target.classList.remove('just-filled'),650)},720)}
  function rgb(hex){const h=hex.replace('#','');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4),16)]}
  function blend(a,b,t){const x=rgb(a),y=rgb(b),v=x.map((n,i)=>Math.round(n+(y[i]-n)*t));return '#'+v.map(n=>n.toString(16).padStart(2,'0')).join('')}
  function blob(ctx,x,y,r,color,seed=1){ctx.save();for(let i=0;i<9;i++){const ang=(i*2.2+seed)*1.7,rr=r*(.58+(i%4)*.08),gx=x+Math.cos(ang)*r*.2,gy=y+Math.sin(ang)*r*.14,g=ctx.createRadialGradient(gx,gy,0,gx,gy,rr);g.addColorStop(0,color);g.addColorStop(.82,color);g.addColorStop(1,color+'22');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(gx,gy,rr*1.18,rr*.82,ang*.12,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=.18;ctx.strokeStyle='#fff';ctx.lineCap='round';ctx.lineWidth=Math.max(3,r*.035);for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(x-r*.55,y-r*.25+i*r*.12);ctx.quadraticCurveTo(x,y-r*.5+i*r*.18,x+r*.55,y-r*.2+i*r*.1);ctx.stroke()}ctx.restore()}
  function showStartingPaint(canvas,color){const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(500,r.width*dpr);canvas.height=Math.max(210,r.height*dpr);const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);blob(c,w*.42,h*.52,Math.min(w,h)*.31,color,1)}
  function initRealMixer(canvas,base,added,ratio,onReady,targetColor){
    const dpr=devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=Math.max(500,rect.width*dpr);canvas.height=Math.max(280,rect.height*dpr);
    const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,target=targetColor||blend(base,added,ratio);c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);
    const unit=Math.min(w,h);blob(c,w*.39,h*.5,unit*(.3-ratio*.165),base,1);blob(c,w*.62,h*.5,unit*(.07+ratio*.33),added,2);
    const br=unit*.14,scratch=document.createElement('canvas'),mask=document.createElement('canvas');scratch.width=scratch.height=mask.width=mask.height=br*2;
    const sc=scratch.getContext('2d'),mc=mask.getContext('2d'),mg=mc.createRadialGradient(br,br,0,br,br,br);mg.addColorStop(0,'#000');mg.addColorStop(.72,'#000d');mg.addColorStop(1,'#0000');mc.fillStyle=mg;mc.fillRect(0,0,br*2,br*2);
    let down=false,last=null,distance=0,ready=false;
    const pos=e=>({x:(e.clientX-rect.left)*w/rect.width,y:(e.clientY-rect.top)*h/rect.height});
    const smudge=(a,b)=>{sc.clearRect(0,0,br*2,br*2);sc.globalCompositeOperation='source-over';sc.drawImage(canvas,a.x-br,a.y-br,br*2,br*2,0,0,br*2,br*2);sc.globalCompositeOperation='destination-in';sc.drawImage(mask,0,0);c.globalAlpha=.5;c.drawImage(scratch,b.x-br,b.y-br);c.globalAlpha=.48;c.strokeStyle=target;c.lineWidth=br*.72;c.lineCap='round';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.globalAlpha=.17;c.strokeStyle='#fff';c.lineWidth=br*.1;c.stroke();c.globalAlpha=1};
    const progress=()=>{const p=Math.min(100,Math.round(distance/(w*2.2)*100));$('.mix-meter i').style.setProperty('--p',p+'%');$('.mix-status').textContent=p>=100?`Mixed color ready: ${target.toUpperCase()}. Confirm to paint it on paper.`:'Keep rubbing through both paint colors—the new color is appearing under your finger.';if(p>=100&&!ready){ready=true;c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);blob(c,w*.5,h*.5,unit*.34,target,4);canvas.classList.add('mix-reveal');onReady()}};
    canvas.onpointerdown=e=>{down=true;last=pos(e);canvas.setPointerCapture(e.pointerId)};
    canvas.onpointermove=e=>{if(!down)return;const p=pos(e),d=Math.hypot(p.x-last.x,p.y-last.y),n=Math.max(1,Math.ceil(d/(br*.28)));for(let i=1;i<=n;i++){const q={x:last.x+(p.x-last.x)*i/n,y:last.y+(p.y-last.y)*i/n};smudge(last,q);last=q}distance+=d;progress()};
    canvas.onpointerup=canvas.onpointercancel=()=>down=false;return ()=>initRealMixer(canvas,base,added,ratio,onReady,targetColor)
  }
  function weightedColor(parts){
    const count=name=>parts.find(p=>p.name===name)?.parts||0,red=count('Red'),yellow=count('Yellow'),blue=count('Blue'),white=count('White'),black=count('Black'),chromatic=red+yellow+blue;let out;
    if(chromatic){const max=Math.max(red,yellow,blue,1),r=red/max,y=yellow/max,b=blue/max,corners=[['#fffdf6',0,0,0],['#dc493a',1,0,0],['#e6b633',0,1,0],['#315e9f',0,0,1],['#ee7827',1,1,0],['#754982',1,0,1],['#47935b',0,1,1],['#795844',1,1,1]],sums=[0,0,0];corners.forEach(([hex,cr,cy,cb])=>{const weight=(cr?r:1-r)*(cy?y:1-y)*(cb?b:1-b);rgb(hex).forEach((n,i)=>sums[i]+=n*weight)});out='#'+sums.map(n=>Math.round(n).toString(16).padStart(2,'0')).join('')}else out=black&&!white?'#292726':'#f9f6ed';
    const total=chromatic+white+black||1;if(white)out=blend(out,'#f9f6ed',white/total);if(black)out=blend(out,'#292726',black/total);return out;
  }
  function initFreeMixer(canvas,parts,onReady){
    const dpr=devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=Math.max(500,rect.width*dpr);canvas.height=Math.max(280,rect.height*dpr);const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,unit=Math.min(w,h),target=weightedColor(parts),root=canvas.closest('.free-studio');c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);
    const active=parts.filter(p=>p.parts>0),positions=[[.3,.38],[.7,.38],[.38,.68],[.63,.68],[.5,.5]];active.forEach((p,i)=>{const at=positions[i%positions.length],size=unit*(.11+Math.min(p.parts,8)*.018);blob(c,w*at[0],h*at[1],size,p.color,i+1)});
    const br=unit*.14,scratch=document.createElement('canvas'),mask=document.createElement('canvas');scratch.width=scratch.height=mask.width=mask.height=br*2;const sc=scratch.getContext('2d'),mc=mask.getContext('2d'),mg=mc.createRadialGradient(br,br,0,br,br,br);mg.addColorStop(0,'#000');mg.addColorStop(.72,'#000d');mg.addColorStop(1,'#0000');mc.fillStyle=mg;mc.fillRect(0,0,br*2,br*2);
    let down=false,last=null,distance=0,ready=false;const pos=e=>({x:(e.clientX-rect.left)*w/rect.width,y:(e.clientY-rect.top)*h/rect.height});const smudge=(a,b)=>{sc.clearRect(0,0,br*2,br*2);sc.globalCompositeOperation='source-over';sc.drawImage(canvas,a.x-br,a.y-br,br*2,br*2,0,0,br*2,br*2);sc.globalCompositeOperation='destination-in';sc.drawImage(mask,0,0);c.globalAlpha=.48;c.drawImage(scratch,b.x-br,b.y-br);c.globalAlpha=.45;c.strokeStyle=target;c.lineWidth=br*.7;c.lineCap='round';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.globalAlpha=1};
    const progress=()=>{const p=Math.min(100,Math.round(distance/(w*2)*100));root.querySelector('.free-mix-meter i').style.setProperty('--p',p+'%');root.querySelector('.free-mix-status').textContent=p>=100?'Your experiment color is ready. Save it, or change the recipe and try again.':'Keep rubbing through every paint color.';if(p>=100&&!ready){ready=true;c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);blob(c,w*.5,h*.5,unit*.34,target,7);onReady(target)}};
    canvas.onpointerdown=e=>{down=true;last=pos(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!down)return;const p=pos(e),d=Math.hypot(p.x-last.x,p.y-last.y),n=Math.max(1,Math.ceil(d/(br*.28)));for(let i=1;i<=n;i++){const q={x:last.x+(p.x-last.x)*i/n,y:last.y+(p.y-last.y)*i/n};smudge(last,q);last=q}distance+=d;progress()};canvas.onpointerup=canvas.onpointercancel=()=>down=false;return target;
  }
  function paintPaperStroke(c,x1,x2,y,color,seed=1){
    c.save();c.lineCap='round';
    for(let i=0;i<9;i++){c.globalAlpha=.09+(i%3)*.055;c.strokeStyle=color;c.lineWidth=24+(i%4)*3;c.beginPath();c.moveTo(x1,y+(i-4)*2.1);c.bezierCurveTo(x1+(x2-x1)*.34,y-5+(i%2)*5,x1+(x2-x1)*.68,y+5-(i%3)*3,x2,y+(i-4)*1.7);c.stroke()}
    c.globalAlpha=.18;c.strokeStyle='#fff';c.lineWidth=3;for(let i=0;i<4;i++){c.beginPath();c.moveTo(x1+5,y-12+i*8);c.lineTo(x2-5,y-10+i*8);c.stroke()}c.restore();
  }
  function initPaperStrip(canvas,m,step,color,onDone){
    const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.fillStyle='#fffef9';c.fillRect(0,0,r.width,r.height);
    const gap=12,col=(r.width-gap*2)/5,y=r.height*.47;
    for(let i=0;i<5;i++){c.fillStyle='#d9cdb9';c.font='600 11px Work Sans';c.textAlign='center';c.fillText((m.short||m.names)[i],gap+col*(i+.5),r.height-16)}
    paintPaperStroke(c,gap+8,gap+col-8,y,m.colors[0],1);
    for(let i=0;i<step;i++)paintPaperStroke(c,gap+col*(i+1)+8,gap+col*(i+2)-8,y,m.colors[i+1],i+2);
    const left=gap+col*(step+1)+6,right=gap+col*(step+2)-6;let down=false,last=null,dist=0,done=false;const p=e=>({x:e.clientX-r.left,y:e.clientY-r.top});
    c.save();c.setLineDash([6,6]);c.strokeStyle='#c8bba8';c.strokeRect(left,22,right-left,r.height-58);c.restore();
    canvas.onpointerdown=e=>{const q=p(e);if(q.x<left||q.x>right)return;down=true;last=q;canvas.setPointerCapture(e.pointerId)};
    canvas.onpointermove=e=>{if(!down)return;const q=p(e);q.x=Math.max(left,Math.min(right,q.x));c.strokeStyle=color;c.lineWidth=31;c.lineCap='round';c.globalAlpha=.72;c.beginPath();c.moveTo(last.x,last.y);c.lineTo(q.x,q.y);c.stroke();c.globalAlpha=.18;c.strokeStyle='#fff';c.lineWidth=3;c.stroke();dist+=Math.hypot(q.x-last.x,q.y-last.y);last=q;if(dist>(right-left)*1.5&&!done){done=true;paintPaperStroke(c,left+5,right-5,y,color,step+5);onDone()}};
    canvas.onpointerup=canvas.onpointercancel=()=>down=false;
  }
  function mixStage(key){
    const m=D.mixes[key];if((state.rounds[key]||0)>=4){stage.innerHTML=shell('Completed ✓',`${m.names[0]} → ${m.names[4]}`,`<p class="lead">Your first color family is safely saved.<br>You can continue, or mix this family again to compare a new result.</p><div class="final-cake-box compact-box"><div class="paintbox-case"><div class="paintbox-wells">${cakeWells()}</div></div></div><div class="actions"><button class="btn light" data-replay-family>Mix this family again</button>${button(key==='warm'?'Continue to Red → Blue':'Continue')}</div>`,'wide');$('[data-replay-family]').onclick=()=>{state.rounds[key]=0;persist();mixStage(key)};return}let step=Math.min(state.rounds[key]||0,3),mixed=false,painted=false;
    const doseLabels=['tiny amount','small amount','medium amount','large amount'];
    const baseParts=[8,6,4,2],addParts=[1,2,4,8],ratios=[.12,.25,.5,.8];
    const renderRound=()=>{
      const addDisplay={warm:'Red',violet:'Blue',green:'Yellow'}[key],addName=addDisplay.toUpperCase(),baseName=m.names[0].toUpperCase(),ratio=ratios[step];
      stage.innerHTML=shell(`Mix ${state.index-2} of 3`,`${m.names[0]} → ${m.names[4]}`,`
        <div class="round-cycle" aria-label="Repeat these three steps for each color"><div class="cycle-step current"><b>1</b><span>Mix <em>this one recipe</em></span></div><i></i><div class="cycle-step"><b>2</b><span>Paint <em>this color on paper</em></span></div><i></i><div class="cycle-step"><b>3</b><span>Save it <em>then start the next recipe</em></span></div></div>
        <div class="mix-guide"><span class="stepno">1</span><div><strong>Mix ${baseParts[step]} parts ${baseName} + ${addParts[step]} part${addParts[step]>1?'s':''} <span style="color:${m.to}">${addName}</span>.</strong><small>One “part” is one similar-sized dab. Use this as a guide—real paints vary.</small></div><div class="guide-side">Color ${step+2} of 5</div></div>
        <p class="one-dose-note">Tap the outlined amount, or drag it onto the palette. Both ways work. The other amounts are for later rounds.</p><div class="paint-dose-tray">${[0,1,2,3].map((x,i)=>`<button class="dose ${i===step?'selected current-dose':i<step?'past-dose':'future-dose'}" draggable="${i===step?'true':'false'}" data-dose="${i}" aria-label="${i===step?'Use now:':i<step?'Completed:':'Later:'} ${addParts[i]} parts ${addName}" ${i===step?'':'disabled'}><i class="dose-dot" style="--s:${28+i*12}px;--c:${m.to}"></i><span>${doseLabels[i]}</span><b class="dose-name" style="color:${m.to}">${addParts[i]} part${addParts[i]>1?'s':''} ${addName}</b><mark>${i===step?'TAP OR DRAG':i<step?'✓ DONE':'LATER'}</mark></button>`).join('')}</div>
        <div class="mixer-layout real"><div class="mix-board real" data-palette><canvas class="mix-canvas real" aria-label="Flat ceramic palette. Drag paint here, then smear both colors together."></canvas><p class="gesture-hint"><span class="finger">☝️</span> Press and rub through both colors.</p><div class="mix-meter"><i></i></div><div class="mix-status">Drag the outlined ${addParts[step]}-part ${addName} dab onto the palette.</div><div class="actions"><button class="btn light" data-reset>Start this mix again</button><button class="btn mix-done" data-mix-done disabled>Step 1 complete → Go to Step 2: Paint on paper</button></div></div></div>
        <div class="drawing-board" hidden><span class="board-pin pin-left"></span><span class="board-pin pin-right"></span><div class="paper-lab"><div class="paper-step-mark">STEP 2 OF THIS ROUND · DO THIS NOW</div><h3>Press and drag inside the dashed paper space.</h3><p class="paper-direct">Paint only the next empty space. Fill it until the color becomes solid—then your paint cake will be saved automatically.</p><div class="paper-action-callout"><span>☝️</span> Start inside the dashed box and rub back and forth</div><canvas class="paper-canvas" aria-label="Paint inside the dashed paper space by pressing and dragging"></canvas><div class="wash-reminder">💧 ${step===3?'Wash the brush before the next color family.':'Keep the brush damp, not dripping.'}</div></div></div>
        <div class="paintbox-live" hidden><div class="paintbox-label"><b>Your real paint cake box</b><small>The first five cakes are your original Red, Yellow, Blue, Black, and White. Every other cake is mixed by you.</small></div><div class="paintbox-case"><div class="paintbox-wells">${cakeWells()}</div></div></div>
        <div class="actions round-next-actions" hidden><button class="btn" data-round-next disabled>${step===3?'Color saved ✓ See my finished paper strip':`Color saved ✓ Next recipe: ${addParts[step+1]} parts ${addDisplay}`}</button></div><div id="mix-end"></div>`,'wide mix-scene');
      const canvas=$('.mix-canvas'),palette=$('[data-palette]');showStartingPaint(canvas,m.from);
      let mixedColor=null;
      const begin=()=>{if(mixed){toast(`${addName} is already added. Mix the paint now.`);return}mixed=true;const tray=$('.paint-dose-tray');tray.classList.add('added');$$('[data-dose]').forEach(d=>{d.disabled=true;d.setAttribute('aria-disabled','true')});const chosen=$(`[data-dose="${step}"]`);chosen.classList.add('added-dose');chosen.querySelector('.dose-name').textContent=`Added ${addParts[step]} part${addParts[step]>1?'s':''} ${addName} ✓`;$('.mix-status').innerHTML=`<b>${addName} added ✓</b> Don’t add more—rub the two colors together.`;toast(`${addParts[step]} part${addParts[step]>1?'s':''} ${addName} added. Now mix.`);initRealMixer(canvas,m.from,m.to,ratio,()=>{mixedColor=m.colors[step+1];$('.mix-status').innerHTML=`<b>${m.names[step+1]}</b><span>${m.notes[step+1]}. Color is continuous—this is a useful relationship name, not one exact formula.</span>`;$('[data-mix-done]').disabled=false;$('[data-mix-done]').focus();toast(`${m.names[step+1]} is ready. Confirm when you are done.`)},m.colors[step+1])};
      $('[data-mix-done]').onclick=()=>{if(!mixedColor)return;const board=$('.drawing-board');$('.round-cycle').classList.add('on-paper');$$('.mix-guide,.one-dose-note,.paint-dose-tray,.mixer-layout').forEach(x=>x.hidden=true);board.hidden=false;initPaperStrip($('.paper-canvas'),m,step,mixedColor,()=>{painted=true;state.rounds[key]=Math.max(state.rounds[key]||0,step+1);persist();$('.round-cycle').classList.add('on-save');board.hidden=true;const box=$('.paintbox-live');box.hidden=false;$('.round-next-actions').hidden=false;$('[data-round-next]').disabled=false;const savedMix=addSaved(mixedColor,m.names[step+1],key==='warm'?'Warm':'Cool');if(savedMix.added){setTimeout(()=>flyToPaintbox(mixedColor,box,savedMix.index),220);toast(`Finished: ${m.names[step+1]}. It is now in your paint box.`)}else{refreshPaintbox();toast(`${m.names[step+1]} is already saved in your paint box.`)}})};
      $$('[data-dose]').forEach(d=>{d.ondragstart=e=>e.dataTransfer.setData('dose',d.dataset.dose);d.onclick=()=>{if(+d.dataset.dose===step)begin();else toast(`Choose ${addParts[step]} part${addParts[step]>1?'s':''} ${addName}.`)}});
      palette.ondragover=e=>e.preventDefault();palette.ondrop=e=>{e.preventDefault();if(+e.dataTransfer.getData('dose')===step)begin();else toast(`Use ${addParts[step]} part${addParts[step]>1?'s':''} ${addName}.`)};
      $('[data-reset]').onclick=()=>{mixed=false;painted=false;renderRound()};
      $('[data-round-next]').onclick=()=>{if(!painted)return;if(step<3){step++;state.rounds[key]=step;persist();mixed=false;painted=false;renderRound()}else{state.rounds[key]=4;persist();finishMix(key,m)}};
    };renderRound();
  }
  function finishMix(key,m){ const paper=key==='warm'?`<div class="paper-card"><p class="instruction">Your five-color paper strip is complete.</p><div class="paper-steps">${m.colors.slice(0,4).map((c,i)=>`<div class="paper-step"><b style="--a:${i?m.colors[i-1]:c};--b:${c}"></b>${['Start clean','Add a tiny touch','Add a little more','Finish the strip'][i]}</div>`).join('')}</div><p class="lead">Wash your brush before the next color family.</p></div>`:''; let result=$('#mix-end');if(!result){result=document.createElement('div');result.id='mix-end';$('.scene').append(result)}result.innerHTML=`<h2 style="margin-top:32px">${m.names[0]} → ${m.names[4]}</h2><p class="lead"><b>Completed ✓ Your color family is saved.</b><br>${m.idea} Different paint, different result—and you can always try again.</p>${paper}<div class="actions"><button class="btn light" data-replay-current>Mix this family again</button>${button(key==='warm'?'Continue to Red → Blue':'Continue')}</div>`;$('[data-replay-current]').onclick=()=>{state.rounds[key]=0;persist();mixStage(key)};$('[data-next]').onclick=next;result.scrollIntoView({behavior:'smooth'}); }
  function realMixPractice(key,kicker,title,note,recipes,nextLabel){
    if((state.rounds[key]||0)>=recipes.length){stage.innerHTML=shell(`${kicker} · Completed ✓`,title,`<p class="lead">These colors are safely saved. Repeat the experiment whenever you want to compare a new result.</p><div class="final-cake-box compact-box"><div class="paintbox-case"><div class="paintbox-wells">${cakeWells()}</div></div></div><div class="actions"><button class="btn light" data-replay-practice>Mix these again</button>${button(nextLabel)}</div>`,'wide');$('[data-replay-practice]').onclick=()=>{state.rounds[key]=0;persist();realMixPractice(key,kicker,title,note,recipes,nextLabel)};return}
    let round=Math.min(state.rounds[key]||0,recipes.length-1),started=false,result=null;const renderRound=()=>{const r=recipes[round];
      stage.innerHTML=shell(kicker,title,`<div class="practice-progress">Color ${round+1} of ${recipes.length}</div><p class="lead">${note}</p><p class="instruction">Take both paint cakes from your box: tap each one, or drag each one onto the palette.</p><div class="practice-source"><button draggable="true" data-take="0" style="--c:${r.base}"><i></i><b>${r.baseName}</b><small>FROM YOUR BOX</small></button><span>+</span><button draggable="true" data-take="1" style="--c:${r.add}"><i></i><b>${r.addName}</b><small>FROM YOUR BOX</small></button></div><div class="mixer-layout real practice-mixer"><div class="mix-board real" data-palette><canvas class="mix-canvas real" aria-label="Mix ${r.baseName} and ${r.addName} by rubbing on the palette"></canvas><p class="gesture-hint"><span class="finger">☝️</span> After both cakes are added, rub them together here.</p><div class="mix-meter"><i></i></div><div class="mix-status">0 of 2 paint cakes added.</div></div></div><div class="actions"><button class="btn" data-save-mix disabled>Save this mixed color</button></div>`,'wide practice-scene');
      const canvas=$('.mix-canvas'),palette=$('[data-palette]'),taken=new Set();showStartingPaint(canvas,'#f8f1e5');
      const take=i=>{if(started||taken.has(i))return;taken.add(i);const b=$(`[data-take="${i}"]`);b.classList.add('taken');b.querySelector('small').textContent='ADDED ✓';$('.mix-status').textContent=`${taken.size} of 2 paint cakes added.`;if(taken.size===2){started=true;$$('[data-take]').forEach(x=>x.disabled=true);initRealMixer(canvas,r.base,r.add,r.ratio,()=>{result=r.result;$('[data-save-mix]').disabled=false;toast(`${r.name} is ready to save.`)},r.result)}};
      $$('[data-take]').forEach(b=>{b.onclick=()=>take(+b.dataset.take);b.ondragstart=e=>e.dataTransfer.setData('practice-paint',b.dataset.take)});palette.ondragover=e=>e.preventDefault();palette.ondrop=e=>{e.preventDefault();take(+e.dataTransfer.getData('practice-paint'))};
      $('[data-save-mix]').onclick=()=>{if(!result)return;addSaved(result,r.name,r.family);round++;state.rounds[key]=round;persist();if(round<recipes.length){started=false;result=null;renderRound()}else{state.rounds[key]=recipes.length;persist();toast(`${recipes.length} new colors are in your box.`);next()}};
    };renderRound();
  }
  function three(){realMixPractice('three','Mix all three','Build brown from colors you already made.','Bring your Orange mixture and original Blue out of the paint box. Mixing them lets all three primaries meet.',[{base:'#dd762f',baseName:'Orange (Yellow + Red)',add:'#315e9f',addName:'a tiny Blue',ratio:.16,result:'#795844',name:'Warm brown',family:'Muted'}],'Continue')}
  function white(){realMixPractice('white','Meet white','White makes colors lighter.','Mix each color yourself. White changes value, but the original hue still remains.',[
    {base:'#e6b633',baseName:'Yellow',add:'#f9f6ed',addName:'White',ratio:.42,result:'#f3df93',name:'Light Yellow',family:'Light'},
    {base:'#dc493a',baseName:'Red',add:'#f9f6ed',addName:'White',ratio:.45,result:'#efa0a1',name:'Pink',family:'Light'},
    {base:'#315e9f',baseName:'Blue',add:'#f9f6ed',addName:'White',ratio:.45,result:'#9eb8d9',name:'Light Blue',family:'Light'},
    {base:'#754982',baseName:'Violet',add:'#f9f6ed',addName:'White',ratio:.48,result:'#bba8cf',name:'Lavender',family:'Light'},
    {base:'#47935b',baseName:'Green',add:'#f9f6ed',addName:'White',ratio:.48,result:'#add2b5',name:'Light Green',family:'Light'}],'Continue')}
  function black(){realMixPractice('black','Meet black','Black is powerful. Use a tiny amount.','Take a color and original Black from your box, then physically mix them. Notice how quickly black changes it.',[
    {base:'#e6b633',baseName:'Yellow',add:'#292726',addName:'tiny Black',ratio:.14,result:'#77704c',name:'Dark Yellow',family:'Dark'},
    {base:'#dc493a',baseName:'Red',add:'#292726',addName:'tiny Black',ratio:.14,result:'#704440',name:'Dark Red',family:'Dark'},
    {base:'#315e9f',baseName:'Blue',add:'#292726',addName:'tiny Black',ratio:.14,result:'#273b55',name:'Dark Blue',family:'Dark'},
    {base:'#47935b',baseName:'Green',add:'#292726',addName:'tiny Black',ratio:.14,result:'#374b3c',name:'Dark Green',family:'Dark'}],'Build my palette')}
  function freeMixStudio(){
    const sources=baseCakes.map(x=>({...x,parts:0}));let readyColor=null,savedCurrent=false;const draw=()=>{const favorites=state.swatches.filter(s=>s.family==='Free Mix');stage.innerHTML=shell('Unlocked · Free experiment','Free Mix Studio',`<p class="lead">Your course completion is safely saved. Now choose your own recipe—tap a paint cake more than once to add more parts.</p><div class="free-studio"><div class="free-sources">${sources.map((s,i)=>`<button data-add-free="${i}" style="--c:${s.color}" class="${s.parts?'active':''}"><i></i><b>${s.name}</b><span>${s.parts||0} part${s.parts===1?'':'s'}</span></button>`).join('')}</div><div class="free-recipe"><b>MY RECIPE</b><span>${sources.filter(s=>s.parts).map(s=>`${s.parts} ${s.name}`).join(' + ')||'Choose at least two different colors'}</span><button data-clear-free>Clear recipe</button></div><div class="mix-board real free-board"><canvas class="mix-canvas real" aria-label="Free mixing palette. Rub all chosen paint colors together."></canvas><p class="gesture-hint"><span class="finger">☝️</span> Rub through every color to discover your mixture.</p><div class="mix-meter free-mix-meter"><i></i></div><div class="mix-status free-mix-status">${sources.filter(s=>s.parts).length>=2?'Mix the paint with your finger or pointer.':'Add two different paint colors to begin.'}</div></div><div class="actions"><button class="btn" data-save-free disabled>${savedCurrent?'Saved ✓':'Save this experiment color'}</button></div><div class="free-favorites"><b>My experiment colors</b><div>${favorites.length?favorites.map(s=>`<i style="--c:${s.color}" title="${s.name}"></i>`).join(''):'<span>Your saved experiments will appear here.</span>'}</div></div></div><div class="actions"><button class="btn light" data-view-palette>View my palette</button><button class="btn light" data-back-finish>Back to lesson finish</button></div>`,'wide free-mix-scene');
      const active=sources.filter(s=>s.parts);const canvas=$('.free-studio canvas');if(active.length>=2){initFreeMixer(canvas,active,color=>{readyColor=color;const save=$('[data-save-free]');if(!savedCurrent)save.disabled=false;save.style.setProperty('--saved-color',color)})}else showStartingPaint(canvas,'#f8f1e5');
      $$('[data-add-free]').forEach(b=>b.onclick=()=>{const s=sources[+b.dataset.addFree];s.parts=Math.min(8,s.parts+1);readyColor=null;savedCurrent=false;draw()});$('[data-clear-free]').onclick=()=>{sources.forEach(s=>s.parts=0);readyColor=null;savedCurrent=false;draw()};$('[data-save-free]').onclick=()=>{if(!readyColor||savedCurrent)return;const number=state.swatches.filter(s=>s.family==='Free Mix').length+1;state.swatches.push({color:readyColor,name:`Free Mix ${number}`,family:'Free Mix'});persist();savedCurrent=true;toast(`Free Mix ${number} saved to your paint box.`);draw()};$('[data-view-palette]').onclick=()=>{state.index=9;render()};$('[data-back-finish]').onclick=()=>{state.index=10;render()};
    };draw();window.scrollTo({top:0,behavior:'smooth'});
  }
  function palette(){const done=!!localStorage.getItem('fei_color_lab_01_complete');stage.innerHTML=shell('Your color collection','You built a real paint box.',`<p class="counter"><span>5</span> original paints + <span>${state.swatches.length}</span> colors mixed by you</p><div class="final-cake-box"><div class="final-box-lid"><b>FEI · COLOR PRACTICE</b><small>MY HAND-MIXED PAINT COLLECTION</small></div><div class="paintbox-case"><div class="paintbox-wells final-wells">${cakeWells(40)}</div></div></div><p class="lead">Every filled cake records a color you actually mixed.</p><details><summary>Original paint or mixed paint?</summary><p>The first five labeled cakes are Red, Yellow, Blue, Black, and White. Every cake after them was created during this lesson.</p></details><div class="actions">${done?'<button class="btn" data-open-free>Open Free Mix Studio</button>':''}${button('Look back')}</div>`,'wide');if(done)$('[data-open-free]').onclick=freeMixStudio;}
  function reflect(){const choices=['Three colors made brown','Tiny changes made new colors','White changed value','Black changed colors quickly'];let record=null;try{record=JSON.parse(localStorage.getItem('fei_color_lab_01_complete')||'null')}catch(e){}const selected=record?.reflection||[];stage.innerHTML=shell(record?'Completed ✓':'One last look',record?'Your palette is saved.':'What surprised you?',`<div class="reflection">${choices.map(x=>`<button class="${selected.includes(x)?'chosen':''}">${x}</button>`).join('')}</div><div class="badge" style="margin:32px auto 18px">PALETTE<br>BUILDER</div><h2>You don’t need every color in the box.</h2><p class="lead">You need to understand how colors relate.<br><b>Your palette is something you can build—and rebuild.</b></p>${classroomDemo()}<div class="actions completion-actions">${record?'<button class="btn" data-open-free>Open Free Mix Studio</button><button class="btn light" data-view-palette>View my palette</button><button class="btn light" data-replay-guided>Play guided lesson again</button>':'<button class="btn" data-save-palette>Save my palette & unlock Free Mix</button>'}<button class="btn light" disabled>Lesson 02 · Coming soon</button></div>`,'wide');$$('.reflection button').forEach(b=>b.onclick=()=>b.classList.toggle('chosen'));if(record){$('[data-open-free]').onclick=freeMixStudio;$('[data-view-palette]').onclick=()=>{state.index=9;render()};$('[data-replay-guided]').onclick=()=>{state.rounds={};state.index=3;persist();render();toast('Guided practice restarted. Your completed palette is still safe.')}}else $('[data-save-palette]').onclick=complete;}
  function complete(){const key='fei_color_lab_01_complete';localStorage.setItem(key,JSON.stringify({completedAt:new Date().toISOString(),swatches:state.swatches,reflection:$$('.reflection .chosen').map(b=>b.textContent)}));try{const p=JSON.parse(sessionStorage.getItem('fei_user_profile')||'{}');p.completedLessons=Array.isArray(p.completedLessons)?p.completedLessons:[];if(!p.completedLessons.includes(D.id)){p.completedLessons.push(D.id);p.totalXP=(p.totalXP||0)+50}sessionStorage.setItem('fei_user_profile',JSON.stringify(p))}catch(e){}toast('Palette saved · Free Mix unlocked');reflect();}
  const renders=[opening,prepare,primaries,()=>mixStage('warm'),()=>mixStage('violet'),()=>mixStage('green'),three,white,black,palette,reflect];
  function render(){rail();renders[state.index]();wireCommon();window.scrollTo({top:0,behavior:'smooth'})}
  $('#sound').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'Sound on':'Sound off';e.currentTarget.setAttribute('aria-pressed',String(state.sound));toast(state.sound?'Gentle sounds on':'Sounds off')};
  document.addEventListener('keydown',e=>{if(e.key==='Escape')prev()});window.addEventListener('resize',()=>{const c=$('.mix-canvas');if(c)c.dispatchEvent(new PointerEvent('pointermove'))});render();
})();
