(() => {
  'use strict';
  const D = window.COLOR_LAB;
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const stage = $('#stage');
  const saved = JSON.parse(localStorage.getItem('fei_color_lab_01') || '{}');
  const paintboxVersion = 2;
  const state = { index: Math.min(saved.index || 0, D.stages.length - 1), swatches: saved.paintboxVersion===paintboxVersion?(saved.swatches || []):[], sound:false };
  const paintColors = ['#e6b633','#dda332','#dc762f','#d95a35','#dc493a','#a84866','#754982','#504f91','#315e9f','#317d78','#47935b','#94aa42','#9a663d','#78513d','#55463e','#f19aa4','#edc7c8','#91acd2','#c8d9e9','#a98cc1','#acd3b6','#6c7652','#7b4642','#263e62'];

  function persist(){ localStorage.setItem('fei_color_lab_01', JSON.stringify({index:state.index,swatches:state.swatches,paintboxVersion})); }
  function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>t.classList.remove('show'),1800); }
  function video(label){ return `<div class="video-slot" data-video-slot="${label}">Teacher video · ${label} · coming soon</div>`; }
  function button(label='Continue', extra=''){ return `<button class="btn" data-next ${extra}>${label}</button>`; }
  function shell(kicker,title,body,cls=''){ return `<section class="scene ${cls}"><div class="eyebrow">${kicker}</div><h2>${title}</h2>${body}</section>`; }
  function next(){ if(state.index < D.stages.length-1){ state.index++; persist(); render(); } }
  function prev(){ if(state.index>0){ state.index--; render(); } }
  function rail(){ $('#paint-trail').innerHTML=D.stages.map((x,i)=>`<button class="trail-dot ${i<state.index?'done':''} ${i===state.index?'current':''}" style="--r:${(i%4-2)*8}deg" aria-label="${x.label}${i===state.index?', current step':''}" ${i>state.index?'disabled':''} data-jump="${i}"></button>`).join(''); }
  function wireCommon(){ $('[data-next]')?.addEventListener('click',next); $$('[data-jump]').forEach(b=>b.addEventListener('click',()=>{state.index=+b.dataset.jump;render()})); stage.focus({preventScroll:true}); }

  function opening(){
    const complete=localStorage.getItem('fei_color_lab_01_complete');
    const showMap=()=>{stage.innerHTML=`<section class="scene course-map-scene"><div class="eyebrow">Skill · Color Practice</div><h1>Your color journey</h1><p class="lead">See where you are. Build a palette that grows with every lesson.</p><div class="course-map"><button class="map-stop available" data-open-why><span class="map-dot tricolor"></span><b>Why Color?</b><small>Start here · 40 sec</small></button><span class="map-line ${complete?'done':''}"></span><button class="map-stop ${complete?'done':'current'}" data-open-lesson><span class="map-dot primary-dot"></span><b>01 · Primary Colors</b><small>${complete?'✓ Complete':'Build your first palette'}</small></button><span class="map-line"></span><button class="map-stop locked" disabled><span class="map-dot analogous-dot"></span><b>02 · Color Neighbors</b><small>Coming soon</small></button><span class="map-line"></span><button class="map-stop locked" disabled><span class="map-dot complement-dot"></span><b>03 · Complementary Colors</b><small>Coming soon</small></button><span class="map-line"></span><button class="map-stop locked" disabled><span class="map-dot warm-dot"></span><b>04 · Warm & Cool</b><small>Coming soon</small></button></div><div class="palette-preview"><span>Your paint box</span><div>${state.swatches.slice(0,14).map(s=>`<i style="--c:${s.color}" title="${s.name}"></i>`).join('')||'<em>Mix colors to fill these wells.</em>'}</div></div></section>`;$('[data-open-why]').onclick=showWhy;$('[data-open-lesson]').onclick=showWhy;};
    const showWhy=()=>{stage.innerHTML=`<section class="scene"><button class="map-back" data-map>← Course map</button><div class="eyebrow">Color Practice · Why Color?</div><h1>Color begins with mixing.</h1><p class="lead">A 40-second moving introduction</p><div class="story-card" id="story"><div class="story-slide story-cover"><div class="story-visual"><i class="story-paint" style="--c:#ee4938"></i><i class="story-paint" style="--c:#f3c529"></i><i class="story-paint" style="--c:#2868c7"></i></div><h3>Why learn color with real paint?</h3><p>Press play. Watch what your hands will discover.</p><button class="btn" data-story-play>Play introduction</button></div><div class="story-slide"><div class="story-icon">🖐️ + 🎨</div><h3>Real paint changes as you mix.</h3><p>You can see it become warmer, cooler, lighter, darker, brighter, or quieter.</p></div><div class="story-slide"><div class="story-visual"><i class="story-paint" style="--c:#f3c529"></i><b>+</b><i class="story-paint" style="--c:#ee4938"></i><b>→</b><i class="story-paint" style="--c:#ed7c2e"></i></div><h3>Your hand learns proportion.</h3><p>A tiny touch makes a tiny shift. More paint makes a stronger change.</p></div><div class="story-slide"><div class="story-icon">🖥️ ↔ 🖼️</div><h3>This helps digital art too.</h3><p>Understanding real color helps every medium—even digital art.</p></div><div class="story-slide"><div class="story-visual"><i class="story-paint" style="--c:#ee4938"></i><i class="story-paint" style="--c:#f3c529"></i><i class="story-paint" style="--c:#2868c7"></i><b>→ 30+</b></div><h3>Lesson 01: build your paint box.</h3><p>Mix on screen, paint on paper, and save every color you make.</p></div><button class="story-skip" data-story-skip>Skip</button><div class="story-progress"></div></div><div class="actions">${button('Prepare my studio','disabled')}</div></section>`;const story=$('#story'),nextBtn=$('[data-next]'),slides=[...story.querySelectorAll('.story-slide')];let timer=null;const finish=()=>{clearTimeout(timer);story.classList.remove('playing');slides.forEach(x=>x.style.display='none');slides.at(-1).style.cssText='display:grid;opacity:1;transform:none;pointer-events:auto';nextBtn.disabled=false;nextBtn.focus();toast('Ready to build your palette.')};$('[data-story-play]').onclick=()=>{story.classList.add('playing');timer=setTimeout(finish,40000)};$('[data-story-skip]').onclick=finish;$('[data-map]').onclick=showMap;nextBtn.onclick=next;};
    showMap();
  }
  function prepare(){
    stage.innerHTML=shell('Prepare your studio','Match these materials at home.',`<p class="lead">Tap each real material when it’s beside you.</p><div class="materials">${D.materials.map((m,i)=>`<button class="material" data-mat="${i}"><span class="material-photo" style="--mx:${i%5};--my:${Math.floor(i/5)}" role="img" aria-label="Photo of ${m[1]}"></span><span>${m[1]}</span></button>`).join('')}</div><p class="lead" style="margin-top:18px">Gouache recommended. Watercolor also works.</p><div class="actions"><button class="btn" data-ready disabled>I have everything</button></div>`,'wide');
    const done=new Set(); $$('[data-mat]').forEach(b=>b.onclick=()=>{ b.classList.toggle('ready'); b.classList.contains('ready')?done.add(b.dataset.mat):done.delete(b.dataset.mat); $('[data-ready]').disabled=done.size<D.materials.length; }); $('[data-ready]').onclick=next;
  }
  function primaries(){
    stage.innerHTML=shell('What are primary colors?','Meet Red, Yellow, and Blue.',`<p class="lead">These are traditional painting primaries—our starting colors.</p><p class="instruction" id="tri-prompt">Drag or tap each color onto the triangle.</p><div class="blob-tray">${[['#dc493a','Red'],['#e6b633','Yellow'],['#315e9f','Blue']].map((c,i)=>`<button class="paint-blob" draggable="true" data-primary="${i}" style="--c:${c[0]}">${c[1]}</button>`).join('')}</div><div class="triangle"><div class="drop" data-i="0">1</div><div class="drop" data-i="1">2</div><div class="drop" data-i="2">3</div><i class="tri-line"></i></div><details><summary>Why these three?</summary><p>They are a practical starting set for learning how paint mixtures relate. They do not literally make every possible pigment.</p></details><div class="actions">${button('Build colors from these three','disabled')}</div>${video('after primary-color introduction')}`);
    let count=0, selected=null; const place=(blob,drop)=>{ if(blob.dataset.placed)return; blob.dataset.placed='1'; blob.style.position='static'; drop.textContent=''; drop.append(blob); count++; $('#tri-prompt').textContent=count===3?'These are our starting colors.':'Choose another color.'; if(count===3){$('[data-next]').disabled=false;toast('Three colors. So many possibilities.')} };
    $$('[data-primary]').forEach(b=>{b.onclick=()=>{if(selected){selected.classList.remove('selected')} selected=b;b.style.outline='3px solid #292622'};b.ondragstart=e=>e.dataTransfer.setData('text',b.dataset.primary)}); $$('.drop').forEach(d=>{d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();place($(`[data-primary="${e.dataTransfer.getData('text')}"]`),d)};d.onclick=()=>{if(selected){place(selected,d);selected=null}}});
  }
  function addSaved(color,name,family){ const old=state.swatches.findIndex(s=>s.name===name);if(old>=0)return {added:false,index:old};state.swatches.push({color,name,family});persist();return {added:true,index:state.swatches.length-1}; }
  function refreshPaintbox(){const wells=$$('.paintbox-wells i');wells.forEach((w,i)=>{const s=state.swatches[i];w.classList.toggle('filled',!!s);if(s){w.style.setProperty('--c',s.color);w.title=s.name}})}
  function flyToPaintbox(color,source,index){const target=$$('.paintbox-wells i')[index];if(!target){refreshPaintbox();return}const a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),sx=Math.max(24,Math.min(innerWidth-64,a.left+a.width/2)),sy=Math.max(20,Math.min(innerHeight-52,a.top+a.height/2)),tx=b.left+b.width/2,ty=b.top+b.height/2,chip=document.createElement('i');chip.className='flying-paint-cake';chip.style.cssText=`--c:${color};left:${sx-20}px;top:${sy-16}px`;document.body.append(chip);requestAnimationFrame(()=>{chip.style.transform=`translate(${tx-sx}px,${ty-sy}px) scale(.62) rotate(8deg)`;chip.style.opacity='.72'});setTimeout(()=>{target.style.setProperty('--c',color);target.classList.add('filled','just-filled');chip.remove();setTimeout(()=>target.classList.remove('just-filled'),650)},720)}
  function rgb(hex){const h=hex.replace('#','');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4),16)]}
  function blend(a,b,t){const x=rgb(a),y=rgb(b),v=x.map((n,i)=>Math.round(n+(y[i]-n)*t));return '#'+v.map(n=>n.toString(16).padStart(2,'0')).join('')}
  function blob(ctx,x,y,r,color,seed=1){ctx.save();for(let i=0;i<9;i++){const ang=(i*2.2+seed)*1.7,rr=r*(.58+(i%4)*.08),gx=x+Math.cos(ang)*r*.2,gy=y+Math.sin(ang)*r*.14,g=ctx.createRadialGradient(gx,gy,0,gx,gy,rr);g.addColorStop(0,color);g.addColorStop(.82,color);g.addColorStop(1,color+'22');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(gx,gy,rr*1.18,rr*.82,ang*.12,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=.18;ctx.strokeStyle='#fff';ctx.lineCap='round';ctx.lineWidth=Math.max(3,r*.035);for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(x-r*.55,y-r*.25+i*r*.12);ctx.quadraticCurveTo(x,y-r*.5+i*r*.18,x+r*.55,y-r*.2+i*r*.1);ctx.stroke()}ctx.restore()}
  function showStartingPaint(canvas,color){const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(500,r.width*dpr);canvas.height=Math.max(210,r.height*dpr);const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);blob(c,w*.42,h*.52,Math.min(w,h)*.31,color,1)}
  function initRealMixer(canvas,base,added,ratio,onReady,targetColor){
    const dpr=devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=Math.max(500,rect.width*dpr);canvas.height=Math.max(280,rect.height*dpr);
    const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,target=targetColor||blend(base,added,ratio);c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);
    const unit=Math.min(w,h);blob(c,w*.39,h*.5,unit*(.3-ratio*.165),base,1);blob(c,w*.62,h*.5,unit*(.07+ratio*.33),added,2);
    const br=unit*.14,scratch=document.createElement('canvas'),mask=document.createElement('canvas');scratch.width=scratch.height=mask.width=mask.height=br*2;
    const sc=scratch.getContext('2d'),mc=mask.getContext('2d'),mg=mc.createRadialGradient(br,br,0,br,br,br);mg.addColorStop(0,'#000');mg.addColorStop(.72,'#000d');mg.addColorStop(1,'#0000');mc.fillStyle=mg;mc.fillRect(0,0,br*2,br*2);
    let down=false,last=null,distance=0,ready=false;
    const pos=e=>({x:(e.clientX-rect.left)*w/rect.width,y:(e.clientY-rect.top)*h/rect.height});
    const smudge=(a,b)=>{sc.clearRect(0,0,br*2,br*2);sc.globalCompositeOperation='source-over';sc.drawImage(canvas,a.x-br,a.y-br,br*2,br*2,0,0,br*2,br*2);sc.globalCompositeOperation='destination-in';sc.drawImage(mask,0,0);c.globalAlpha=.5;c.drawImage(scratch,b.x-br,b.y-br);c.globalAlpha=.48;c.strokeStyle=target;c.lineWidth=br*.72;c.lineCap='round';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.globalAlpha=.17;c.strokeStyle='#fff';c.lineWidth=br*.1;c.stroke();c.globalAlpha=1};
    const progress=()=>{const p=Math.min(100,Math.round(distance/(w*2.2)*100));$('.mix-meter i').style.setProperty('--p',p+'%');$('.mix-status').textContent=p>=100?`Mixed color ready: ${target.toUpperCase()}. Confirm to paint it on paper.`:'Keep rubbing through both paint colors—the new color is appearing under your finger.';if(p>=100&&!ready){ready=true;c.fillStyle='#f8f1e5';c.fillRect(0,0,w,h);blob(c,w*.5,h*.5,unit*.34,target,4);canvas.classList.add('mix-reveal');onReady()}};
    canvas.onpointerdown=e=>{down=true;last=pos(e);canvas.setPointerCapture(e.pointerId)};
    canvas.onpointermove=e=>{if(!down)return;const p=pos(e),d=Math.hypot(p.x-last.x,p.y-last.y),n=Math.max(1,Math.ceil(d/(br*.28)));for(let i=1;i<=n;i++){const q={x:last.x+(p.x-last.x)*i/n,y:last.y+(p.y-last.y)*i/n};smudge(last,q);last=q}distance+=d;progress()};
    canvas.onpointerup=canvas.onpointercancel=()=>down=false;return ()=>initRealMixer(canvas,base,added,ratio,onReady,targetColor)
  }
  function paintPaperStroke(c,x1,x2,y,color,seed=1){
    c.save();c.lineCap='round';
    for(let i=0;i<9;i++){c.globalAlpha=.09+(i%3)*.055;c.strokeStyle=color;c.lineWidth=24+(i%4)*3;c.beginPath();c.moveTo(x1,y+(i-4)*2.1);c.bezierCurveTo(x1+(x2-x1)*.34,y-5+(i%2)*5,x1+(x2-x1)*.68,y+5-(i%3)*3,x2,y+(i-4)*1.7);c.stroke()}
    c.globalAlpha=.18;c.strokeStyle='#fff';c.lineWidth=3;for(let i=0;i<4;i++){c.beginPath();c.moveTo(x1+5,y-12+i*8);c.lineTo(x2-5,y-10+i*8);c.stroke()}c.restore();
  }
  function initPaperStrip(canvas,m,step,color,onDone){
    const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.fillStyle='#fffef9';c.fillRect(0,0,r.width,r.height);
    const gap=12,col=(r.width-gap*2)/5,y=r.height*.47;
    for(let i=0;i<5;i++){c.fillStyle='#d9cdb9';c.font='600 11px Work Sans';c.textAlign='center';c.fillText(m.names[i],gap+col*(i+.5),r.height-16)}
    paintPaperStroke(c,gap+8,gap+col-8,y,m.colors[0],1);
    for(let i=0;i<step;i++)paintPaperStroke(c,gap+col*(i+1)+8,gap+col*(i+2)-8,y,m.colors[i+1],i+2);
    const left=gap+col*(step+1)+6,right=gap+col*(step+2)-6;let down=false,last=null,dist=0,done=false;const p=e=>({x:e.clientX-r.left,y:e.clientY-r.top});
    c.save();c.setLineDash([6,6]);c.strokeStyle='#c8bba8';c.strokeRect(left,22,right-left,r.height-58);c.restore();
    canvas.onpointerdown=e=>{const q=p(e);if(q.x<left||q.x>right)return;down=true;last=q;canvas.setPointerCapture(e.pointerId)};
    canvas.onpointermove=e=>{if(!down)return;const q=p(e);q.x=Math.max(left,Math.min(right,q.x));c.strokeStyle=color;c.lineWidth=31;c.lineCap='round';c.globalAlpha=.72;c.beginPath();c.moveTo(last.x,last.y);c.lineTo(q.x,q.y);c.stroke();c.globalAlpha=.18;c.strokeStyle='#fff';c.lineWidth=3;c.stroke();dist+=Math.hypot(q.x-last.x,q.y-last.y);last=q;if(dist>(right-left)*1.5&&!done){done=true;paintPaperStroke(c,left+5,right-5,y,color,step+5);onDone()}};
    canvas.onpointerup=canvas.onpointercancel=()=>down=false;
  }
  function mixStage(key){
    const m=D.mixes[key];let step=0,mixed=false,painted=false;
    const doseLabels=['tiny amount','small amount','medium amount','large amount'];
    const baseParts=[8,6,4,2],addParts=[1,2,4,8],ratios=[.12,.25,.5,.8];
    const renderRound=()=>{
      const addName=m.names[4].toUpperCase(),baseName=m.names[0].toUpperCase(),ratio=ratios[step];
      stage.innerHTML=shell(`Mix ${state.index-2} of 3`,`${m.names[0]} → ${m.names[4]}`,`
        <div class="round-cycle" aria-label="Repeat these three steps for each color"><div class="cycle-step current"><b>1</b><span>Mix <em>this one recipe</em></span></div><i></i><div class="cycle-step"><b>2</b><span>Paint <em>this color on paper</em></span></div><i></i><div class="cycle-step"><b>3</b><span>Save it <em>then start the next recipe</em></span></div></div>
        <div class="mix-guide"><span class="stepno">1</span><div><strong>Mix ${baseParts[step]} parts ${baseName} + ${addParts[step]} part${addParts[step]>1?'s':''} <span style="color:${m.to}">${addName}</span>.</strong><small>One “part” is one similar-sized dab. Use this as a guide—real paints vary.</small></div><div class="guide-side">Color ${step+2} of 5</div></div>
        <p class="one-dose-note">Use only the outlined amount now. The other amounts belong to later rounds.</p><div class="paint-dose-tray">${[0,1,2,3].map((x,i)=>`<button class="dose ${i===step?'selected current-dose':i<step?'past-dose':'future-dose'}" draggable="${i===step?'true':'false'}" data-dose="${i}" aria-label="${i===step?'Use now:':i<step?'Completed:':'Later:'} ${addParts[i]} parts ${addName}" ${i===step?'':'disabled'}><i class="dose-dot" style="--s:${28+i*12}px;--c:${m.to}"></i><span>${doseLabels[i]}</span><b class="dose-name" style="color:${m.to}">${addParts[i]} part${addParts[i]>1?'s':''} ${addName}</b><mark>${i===step?'USE NOW':i<step?'✓ DONE':'LATER'}</mark></button>`).join('')}</div>
        <div class="mixer-layout real"><div class="mix-board real" data-palette><canvas class="mix-canvas real" aria-label="Flat ceramic palette. Drag paint here, then smear both colors together."></canvas><p class="gesture-hint"><span class="finger">☝️</span> Press and rub through both colors.</p><div class="mix-meter"><i></i></div><div class="mix-status">Drag the outlined ${addParts[step]}-part ${addName} dab onto the palette.</div><div class="actions"><button class="btn light" data-reset>Start this mix again</button><button class="btn mix-done" data-mix-done disabled>Step 1 complete → Go to Step 2: Paint on paper</button></div></div></div>
        <div class="drawing-board" hidden><span class="board-pin pin-left"></span><span class="board-pin pin-right"></span><div class="paper-lab"><div class="paper-step-mark">STEP 2 OF THIS ROUND · DO THIS NOW</div><h3>Press and drag inside the dashed paper space.</h3><p class="paper-direct">Paint only the next empty space. Fill it until the color becomes solid—then your paint cake will be saved automatically.</p><div class="paper-action-callout"><span>☝️</span> Start inside the dashed box and rub back and forth</div><canvas class="paper-canvas" aria-label="Paint inside the dashed paper space by pressing and dragging"></canvas><div class="wash-reminder">💧 ${step===3?'Wash the brush before adding clean '+m.names[4]+'.':'Keep the brush damp, not dripping.'}</div></div></div>
        <div class="paintbox-live"><div class="paintbox-label"><b>Your paint cake box</b><small>Empty at first. Each finished mixture becomes one new paint cake.</small></div><div class="paintbox-case"><div class="paintbox-wells">${Array.from({length:15},(_,i)=>state.swatches[i]?`<i class="filled" style="--c:${state.swatches[i].color}" title="${state.swatches[i].name}"></i>`:'<i></i>').join('')}</div></div></div>
        <div class="actions"><button class="btn" data-round-next disabled>${step===3?'Color saved ✓ See my finished paper strip':`Color saved ✓ Next recipe: ${addParts[step+1]} parts ${m.names[4]}`}</button></div><div id="mix-end"></div>`,'wide');
      const canvas=$('.mix-canvas'),palette=$('[data-palette]');showStartingPaint(canvas,m.from);
      let mixedColor=null;
      const begin=()=>{if(mixed){toast(`${addName} is already added. Mix the paint now.`);return}mixed=true;const tray=$('.paint-dose-tray');tray.classList.add('added');$$('[data-dose]').forEach(d=>{d.disabled=true;d.setAttribute('aria-disabled','true')});const chosen=$(`[data-dose="${step}"]`);chosen.classList.add('added-dose');chosen.querySelector('.dose-name').textContent=`Added ${addParts[step]} part${addParts[step]>1?'s':''} ${addName} ✓`;$('.mix-status').innerHTML=`<b>${addName} added ✓</b> Don’t add more—rub the two colors together.`;toast(`${addParts[step]} part${addParts[step]>1?'s':''} ${addName} added. Now mix.`);initRealMixer(canvas,m.from,m.to,ratio,()=>{mixedColor=m.colors[step+1];$('[data-mix-done]').disabled=false;$('[data-mix-done]').focus();toast('Looks mixed. Confirm when you are done.')},m.colors[step+1])};
      $('[data-mix-done]').onclick=()=>{if(!mixedColor)return;const board=$('.drawing-board');$('.round-cycle').classList.add('on-paper');palette.classList.add('finished-step');board.hidden=false;board.scrollIntoView({behavior:'smooth',block:'center'});initPaperStrip($('.paper-canvas'),m,step,mixedColor,()=>{painted=true;$('.round-cycle').classList.add('on-save');$('.paper-action-callout').innerHTML='<span>✓</span> Paper color complete — it is now entering your paint box';$('[data-round-next]').disabled=false;const savedMix=addSaved(mixedColor,m.names[step+1],key==='warm'?'Warm':'Cool');if(savedMix.added){$('.paintbox-live').scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>flyToPaintbox(mixedColor,$('.paper-canvas'),savedMix.index),480);toast(`Finished: ${m.names[step+1]}. Watch it enter your paint box.`)}else{refreshPaintbox();toast(`${m.names[step+1]} is already saved in your paint box.`)}})};
      $$('[data-dose]').forEach(d=>{d.ondragstart=e=>e.dataTransfer.setData('dose',d.dataset.dose);d.onclick=()=>{if(+d.dataset.dose===step)begin();else toast(`Choose ${addParts[step]} part${addParts[step]>1?'s':''} ${addName}.`)}});
      palette.ondragover=e=>e.preventDefault();palette.ondrop=e=>{e.preventDefault();if(+e.dataTransfer.getData('dose')===step)begin();else toast(`Use ${addParts[step]} part${addParts[step]>1?'s':''} ${addName}.`)};
      $('[data-reset]').onclick=()=>{mixed=false;painted=false;renderRound()};
      $('[data-round-next]').onclick=()=>{if(!painted)return;if(step<3){step++;mixed=false;painted=false;renderRound()}else finishMix(key,m)};
    };renderRound();
  }
  function finishMix(key,m){ const paper=key==='warm'?`<div class="paper-card"><p class="instruction">Your five-color paper strip is complete.</p><div class="paper-steps">${m.colors.slice(0,4).map((c,i)=>`<div class="paper-step"><b style="--a:${i?m.colors[i-1]:c};--b:${c}"></b>${['Start clean','Add a tiny touch','Add a little more','Finish the strip'][i]}</div>`).join('')}</div><p class="lead">Wash your brush before the next color family.</p></div>`:''; let result=$('#mix-end');if(!result){result=document.createElement('div');result.id='mix-end';$('.scene').append(result)}result.innerHTML=`<h2 style="margin-top:32px">${m.names[0]} → ${m.names[4]}</h2><p class="lead"><b>${m.idea}</b><br>Different paint, different result. That works too.</p>${paper}<div class="actions">${button(key==='warm'?'Continue to Red → Blue':'Continue')}</div>`; $('[data-next]').onclick=next; result.scrollIntoView({behavior:'smooth'}); }
  function three(){
    stage.innerHTML=shell('Mix all three','What happens when all three meet?',`${video('before three-color mixing')}<p class="instruction">Tap each step to discover.</p><div class="discovery"><button class="bigpaint" style="--c:#dc762f" data-discover="0" aria-label="Bright orange"></button><span class="operator">+</span><button class="bigpaint" style="--c:#315e9f" data-discover="1" aria-label="A small touch of blue"></button><span class="operator">=</span><button class="bigpaint" style="--c:#e7dcc9" data-discover="2" aria-label="Hidden result"></button></div><div id="three-note"></div>`);
    const seen=new Set();$$('[data-discover]').forEach(b=>b.onclick=()=>{seen.add(b.dataset.discover);if(b.dataset.discover==='2'&&seen.has('0')&&seen.has('1')){b.style.setProperty('--c','#795844');b.setAttribute('aria-label','Warm muted brown');$('#three-note').innerHTML=`<h2 style="margin-top:28px">Muted. Earthy. Brown.</h2><p class="lead">You did not use black.<br><b>Colors can neutralize each other.</b></p><div class="actions">${button()}</div>`;$('[data-next]').onclick=next;addSaved('#795844','Warm brown','Muted');toast('Three primaries made a neutral.')}else toast(b.dataset.discover==='0'?'Bright orange.':'Now add just a touch.');});
  }
  function white(){
    const tests=[['#e6b633','Yellow','#f3df93'],['#dc493a','Red','#efa0a1'],['#315e9f','Blue','#9eb8d9'],['#754982','Violet','#bba8cf'],['#47935b','Green','#add2b5']];stage.innerHTML=shell('Meet white','White makes colors lighter.',`${video('before white and black')}<p class="instruction">Tap each color to add white.</p><div class="test-grid">${tests.map((t,i)=>`<button class="test-card" data-test="${i}"><div class="paintband" style="--a:${t[0]};--b:${t[2]};--p:48%"></div>${t[1]} + White</button>`).join('')}</div><details class="vocab"><summary>New word: VALUE</summary><p>Value means how light or dark a color is.</p></details><div class="actions">${button('Continue','disabled')}</div>`,'wide');
    const seen=new Set();$$('[data-test]').forEach((b,i)=>b.onclick=()=>{b.classList.add('done');seen.add(i);addSaved(tests[i][2],i===1?'Pink':i===3?'Lavender':`Light ${tests[i][1]}`,'Light');toast('See it get lighter?');if(seen.size>=3)$('[data-next]').disabled=false});
  }
  function black(){
    const tests=[['#e6b633','Yellow','#77704c'],['#dc493a','Red','#704440'],['#315e9f','Blue','#273b55'],['#47935b','Green','#374b3c']];stage.innerHTML=shell('Meet black','Black is powerful. Use a little.',`<p class="instruction">Tap to add one tiny touch.</p><div class="test-grid">${tests.map((t,i)=>`<button class="test-card" data-test="${i}"><div class="paintband" style="--a:${t[0]};--b:${t[2]};--p:20%"></div>${t[1]} + tiny black</button>`).join('')}</div><div class="compare-card" style="margin-top:20px"><b>Dark does not always mean black.</b><p>Primary-mixed brown stays colorful. Black mutes quickly.</p></div><div class="actions">${button('Build my palette','disabled')}</div>`,'wide');const seen=new Set();$$('[data-test]').forEach((b,i)=>b.onclick=()=>{b.classList.add('done');seen.add(i);addSaved(tests[i][2],`Dark ${tests[i][1]}`,'Dark');toast('A tiny amount changes it quickly.');if(seen.size>=3)$('[data-next]').disabled=false});
  }
  function palette(){ const all=[...new Map([...state.swatches,...paintColors.map((c,i)=>({color:c,name:`Mix ${i+1}`,family:i<5?'Warm':i<12?'Cool':i<20?'Light':'Dark'}))].map(x=>[x.color,x])).values()];stage.innerHTML=shell('Your color collection','You built this palette.',`<p class="counter">You started with <span>5</span> colors.<br>You discovered <span>${all.length}</span> possibilities.</p><div class="final-palette" aria-label="Your saved paint swatches">${all.map((x,i)=>`<i class="final-chip" title="${x.name}" style="--c:${x.color};--d:${i*.025}s"></i>`).join('')}</div><p class="lead">Warm · Cool · Light · Dark · Muted</p><details><summary>Do colors ever “lean”?</summary><p>Not every red, yellow, or blue is the same. Some lean warmer or cooler. We’ll explore that in another Color Practice lesson.</p></details><div class="actions">${button('Look back')}</div>`,'wide'); }
  function reflect(){ stage.innerHTML=shell('One last look','What surprised you?',`<div class="reflection">${['Three colors made brown','Tiny changes made new colors','White changed value','Black changed colors quickly'].map(x=>`<button>${x}</button>`).join('')}</div><div class="badge" style="margin:32px auto 18px">PALETTE<br>BUILDER</div><h2>You don’t need every color in the box.</h2><p class="lead">You need to understand how colors relate.<br><b>Your palette is something you can build.</b></p>${video('optional final recap')}<div class="actions"><button class="btn" data-save-palette>Save my palette</button><button class="btn light" disabled>Lesson 02 · Coming soon</button></div>`);$$('.reflection button').forEach(b=>b.onclick=()=>b.classList.toggle('chosen'));$('[data-save-palette]').onclick=complete; }
  function complete(){ const key='fei_color_lab_01_complete';localStorage.setItem(key,JSON.stringify({completedAt:new Date().toISOString(),swatches:state.swatches,reflection:$$('.reflection .chosen').map(b=>b.textContent)}));try{const p=JSON.parse(sessionStorage.getItem('fei_user_profile')||'{}');p.completedLessons=Array.isArray(p.completedLessons)?p.completedLessons:[];if(!p.completedLessons.includes(D.id)){p.completedLessons.push(D.id);p.totalXP=(p.totalXP||0)+50}sessionStorage.setItem('fei_user_profile',JSON.stringify(p))}catch(e){}toast('Palette saved · Badge earned');$('[data-save-palette]').textContent='Palette saved ✓'; }
  const renders=[opening,prepare,primaries,()=>mixStage('warm'),()=>mixStage('violet'),()=>mixStage('green'),three,white,black,palette,reflect];
  function render(){rail();renders[state.index]();wireCommon();window.scrollTo({top:0,behavior:'smooth'})}
  $('#sound').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'Sound on':'Sound off';e.currentTarget.setAttribute('aria-pressed',String(state.sound));toast(state.sound?'Gentle sounds on':'Sounds off')};
  document.addEventListener('keydown',e=>{if(e.key==='Escape')prev()});window.addEventListener('resize',()=>{const c=$('.mix-canvas');if(c)c.dispatchEvent(new PointerEvent('pointermove'))});render();
})();
