/* Native vector storyboard studies: the same art is used for both framings. */
window.CloseupVisuals={
 comparisons:[
  {id:'ecu_mug',sceneKey:'glassOfWater',title:'The hand on the mug',crop:[330,170,230,172.5],focus:'The fingers holding the handle',why:'Close-Up shows the hand, mug and meal. Extreme Close-Up fills the frame with the grip: a small movement becomes the story.',framing:'Draw only the fingers and the curve of the handle. What does the grip tell us?'},
  {id:'ecu_feet',sceneKey:'walkingFeet',title:'One small step',crop:[175,380,290,217.5],focus:'The shoe, heel and contact with the floor',why:'Close-Up shows two feet walking. Extreme Close-Up isolates one step, so the lifted heel and sole carry the movement.',framing:'Draw one shoe meeting or leaving the ground. Show the tiny action clearly.'},
  {id:'ecu_face',sceneKey:'frightenedFace',title:'Fear in one eye',crop:[230,160,160,120],focus:'The widened eye and worried eyebrow',why:'Close-Up shows the frightened face and cushion. Extreme Close-Up crops into the expression: a widened eye and raised brow make fear the focus.',framing:'Draw one eye and its eyebrow. Keep the same emotion, but let one detail fill the frame.'}
 ],
 image(key,box='0 0 800 600',id=''){return `<svg ${id?`id="${id}"`:''} class="study-image" viewBox="${box}" role="img" aria-label="${key==='frightenedFace'?'A frightened face holding a cushion':key==='glassOfWater'?'A hand holding a mug beside a plate':key==='walkingFeet'?'Two shoes taking a step':key==='unlockingDoor'?'A hand turning a door handle as a face watches':'Hands passing a note under a table'}"><image href="scene-art/${key}.svg" width="800" height="600"/></svg>`},
 scene(story,index){return `<div class="step-inner study-shell"><div class="study-kicker">CLOSE-UP · STORY ${index+1} / 5</div><h2 class="step-title">${story.title}</h2><p class="step-sub">${story.situationLine}</p><div class="study-frame">${this.image(story.sceneKey)}</div><p class="study-instruction">${story.framing}</p><button class="study-reference" onclick="openTeacherLightbox('${story.id}')">▶ Teacher’s Quick Sketch</button></div>`},
 compare(index){const c=this.comparisons[index];return `<div class="step-inner study-shell"><div class="study-kicker">SAME STORY · MOVE CLOSER · ${index+1} / 3</div><h2 class="step-title">${c.title}</h2><div class="study-pair"><figure><figcaption>Close-Up <small>See the action</small></figcaption>${this.image(c.sceneKey)}</figure><figure><figcaption id="cropLabel">Move the camera closer</figcaption>${this.image(c.sceneKey,'0 0 800 600','cropStudy')}</figure></div><label class="study-zoom">Close-Up <input id="cropSlider" type="range" min="0" max="100" value="0" aria-label="Move from close-up to extreme close-up"> Extreme Close-Up</label><p class="study-instruction" id="cropFocus">Slide to fill the frame with one detail.</p><p class="study-why">${c.why}</p></div>`},
 mountComparison(index){const c=this.comparisons[index],slider=document.getElementById('cropSlider'),view=document.getElementById('cropStudy');slider.oninput=()=>{const t=Number(slider.value)/100;view.setAttribute('viewBox',[c.crop[0]*t,c.crop[1]*t,800+(c.crop[2]-800)*t,600+(c.crop[3]-600)*t].join(' '));document.getElementById('cropLabel').textContent=t>.9?'Extreme Close-Up':'Moving closer…';document.getElementById('cropFocus').textContent=t>.9?c.focus:'Keep the same story. Bring the camera closer.'}},
 practice(story){return `<div class="practice-ref-video">${this.image(story.sceneKey,story.crop.join(' '))}</div><p class="study-instruction">${story.focus}</p>`}
};
