(()=>{
const C=window.COLOR_SHAPE_LESSON,root=document.querySelector('#stage'),bar=document.querySelector('.progress i'),mark=document.querySelector('.mark b'),toast=document.querySelector('.toast');
const COLORS=['#ef4b4b','#f0823e','#f1c83f','#8fcf55','#3ea46c','#3aaab0','#3978d1','#6551b9','#9147a8','#cc4d92','#eb6680','#ef4b4b'];
const families=[
 {name:'Sunlit warm',colors:['#f5d64a','#f1ad3e','#ed7b3c','#d94f45']},
 {name:'Warm violet',colors:['#ed7659','#d75066','#a7488a','#6d4e9f']},
 {name:'Cool violet',colors:['#dc557f','#a94a9a','#6a56ad','#436cc3']},
 {name:'Garden cool',colors:['#3978c8','#35a0a5','#54b86c','#a5cb52']}
];
let state=JSON.parse(localStorage.getItem(C.key)||'null')||{page:0,family:0,shape:0,paint:{},pairs:[],complete:false};let selected=null,sound=false;
if(C.mode==='neighbors'&&state.valueStudioVersion!==1){state.valueStudioVersion=1;state.valueStep=0;['0','1','2'].forEach(i=>delete state.paint[`value-cube-${i}`]);localStorage.setItem(C.key,JSON.stringify(state))}
const save=()=>localStorage.setItem(C.key,JSON.stringify(state));const say=t=>{toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)};
function tone(n=420){if(!sound)return;const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=n;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.22);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.23)}
document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'Sound on':'Sound off';tone(520)};
function wheel(label='Color wheel',active=[]){return `<div class="wheel" data-label="${label}">${COLORS.slice(0,12).map((c,i)=>{const a=i*30-90,b=(i+1)*30-90,pt=x=>`${50+50*Math.cos(x*Math.PI/180)}% ${50+50*Math.sin(x*Math.PI/180)}%`;return `<button class="wedge ${active.includes(i)?'on':''}" data-wedge="${i}" style="--c:${c};--a:${pt(a)};--b:${pt(b)}" aria-label="Color ${i+1}"></button>`}).join('')}</div>`}
function shell(title,sub,body,actions=''){bar.style.setProperty('--p',`${(state.page+1)/C.pages*100}%`);mark.textContent=C.number;root.innerHTML=`<section class="page"><header class="heading"><div class="eyebrow">${C.kicker}</div><h2>${title}</h2><p>${sub}</p></header><div class="workspace">${body}</div><footer class="actions">${actions}</footer></section>`}
const next=(n=state.page+1)=>{selected=null;state.page=Math.max(0,Math.min(C.pages-1,n));save();render()};const buttons=(ok=true,label='Continue')=>`${state.page?'<button class="btn secondary" data-back>Back</button>':''}<button class="btn" data-next ${ok?'':'disabled'}>${label} →</button>`;
function bindNav(){const n=document.querySelector('[data-next]'),b=document.querySelector('[data-back]');if(n)n.onclick=()=>next();if(b)b.onclick=()=>next(state.page-1)}
function processVideo(file,poster,label){const media=file==='value-process.mp4'?`<iframe src="https://customer-a78os4oj56dr67ab.cloudflarestream.com/618777663c36cdbc30caefa70d5070c4/iframe?poster=https%3A%2F%2Fcustomer-a78os4oj56dr67ab.cloudflarestream.com%2F618777663c36cdbc30caefa70d5070c4%2Fthumbnails%2Fthumbnail.jpg%3Ftime%3D6s%26height%3D600&muted=true&loop=true&controls=true" title="${label}" loading="lazy" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`:`<video src="../color-practice-shapes/assets/${file}" poster="../color-practice-shapes/assets/${poster}" autoplay muted loop playsinline controls aria-label="${label}"></video>`;return `<div class="process-demo">${media}<small><b>REAL CLASSROOM PROCESS · MUTED</b><br>${label}. Pause whenever you want to look closely.</small></div>`}
function intro(){const copy=C.mode==='neighbors'?['Colors can sit beside each other.','Neighbors']:['Some colors face each other.','Opposites'];shell(C.title,copy[0],`<div class="intro-visual"><div class="intro-orbit"><span style="--c:${C.mode==='neighbors'?'#f4ce47':'#f3ca47'};--x:5%;--y:14%"></span><span style="--c:${C.mode==='neighbors'?'#e76443':'#7754aa'};--x:78%;--y:65%"></span></div>${wheel(copy[1],C.mode==='neighbors'?[1,2,3]:[2,8])}</div>`,buttons(true,'Enter the studio'));bindNav();document.querySelectorAll('.wedge').forEach(w=>w.onclick=()=>tone(280+Number(w.dataset.wedge)*24))}
function valueBridge(){const recipes=[
  {name:'Light value',color:'#e8e7ea',parts:['4 drops','3 parts','tiny touch'],note:'Mostly water and white, with only a touch of black.'},
  {name:'Middle value',color:'#aaa8ad',parts:['2 drops','2 parts','2 parts'],note:'Bring black and white closer to balance.'},
  {name:'Dark value',color:'#56545b',parts:['1 drop','1 part','4 parts'],note:'More black makes the value darker.'}
],step=Math.min(state.valueStep||0,3),done=step===3;
const right=done?`<section class="value-digital value-review"><div class="eyebrow">VALUE SCALE COMPLETE</div><h3>Light → Middle → Dark</h3><div class="value-scale">${recipes.map(r=>`<i style="--c:${r.color}"><span>${r.name}</span></i>`).join('')}</div><p>Value tells us how light or dark a color appears. These three values make the cube turn in space.</p>${shapeHTML('cube','value')}</section>`:`<section class="value-digital"><div class="value-stepper">${recipes.map((r,i)=>`<i class="${i<step?'done':''} ${i===step?'on':''}">${i+1}</i>`).join('')}<b>Mix ${step+1} of 3 · ${recipes[step].name}</b></div><p>${recipes[step].note}</p><div class="value-sources">${['Water','White','Black'].map((n,i)=>`<button data-value-source="${i}" style="--c:${['#bfe8f3','#f8f7f1','#29272b'][i]}"><i></i><b>${n}</b><small>${recipes[step].parts[i]}</small></button>`).join('')}</div><canvas class="value-well" aria-label="Digital palette. Add water, white and black, then rub to mix."></canvas><div class="value-mix-status">Add all three ingredients, then rub them together.</div><button class="btn value-paint" disabled>Paint this ${recipes[step].name.toLowerCase()} on the cube</button><div class="value-cube-preview">${shapeHTML('cube','value')}</div></section>`;
shell('Value comes before color','Watch the real paper demonstration on the left. On the right, mix Black, White and Water yourself.',`<div class="value-studio"><section class="value-teacher"><div class="eyebrow">TEACHER DEMONSTRATION</div><h3>Watch the paint change.</h3>${processVideo('value-process.mp4','neighbors-demo.jpg','Only the paper, paint and brush: light, middle and dark')}</section>${right}</div>`,buttons(done,'Next: Find value inside color'));bindNav();if(!done)initValueMixer(recipes[step],step)}
function initValueMixer(recipe,step){const canvas=document.querySelector('.value-well'),ctx=canvas.getContext('2d'),status=document.querySelector('.value-mix-status'),paint=document.querySelector('.value-paint'),added=new Set();canvas.width=620;canvas.height=250;ctx.fillStyle='#f2eee7';ctx.fillRect(0,0,canvas.width,canvas.height);const blobs=['#bfe8f3','#f8f7f1','#29272b'];function blob(i){ctx.globalAlpha=i===0?.42:1;ctx.fillStyle=blobs[i];ctx.beginPath();ctx.ellipse(150+i*155,125,68-i*8,46+i*4,(i-1)*.18,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}document.querySelectorAll('[data-value-source]').forEach(b=>b.onclick=()=>{const i=+b.dataset.valueSource;if(added.has(i))return say(`${['Water','White','Black'][i]} is already on your palette.`);added.add(i);b.classList.add('added');blob(i);tone(300+i*80);status.textContent=added.size===3?'Now rub through all three paints.':'Add the remaining ingredients.'});let down=false,last=null,progress=0;const pos=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};canvas.onpointerdown=e=>{if(added.size<3)return say('Add Water, White and Black first.');down=true;last=pos(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!down)return;const p=pos(e);progress=Math.min(100,progress+3);ctx.strokeStyle=recipe.color;ctx.globalAlpha=.24+.65*progress/100;ctx.lineWidth=42;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.globalAlpha=1;last=p;status.textContent=progress<100?`Keep mixing · ${progress}%`:`${recipe.name} ready. Paint it onto the cube.`;if(progress>=100)paint.disabled=false};canvas.onpointerup=canvas.onpointercancel=()=>{down=false};paint.onclick=()=>{state.paint[`value-cube-${step}`]=recipe.color;state.valueStep=step+1;save();tone(560+step*70);render()}}
function family(){state.family=0;shell('Now find value inside color','Value is not only black and white. In this warm neighbor family, Yellow reads lightest and Red reads darker.',`<div class="family-builder"><div>${wheel('Yellow → Red value path',[1,2,3,4])}</div><div class="family-card"><div class="eyebrow">VALUE IN COLOR</div><h3>Yellow → Orange → Red</h3><div class="family-strip">${families[0].colors.map((c,i)=>`<i style="--c:${c}" data-v="${['Lightest','Light-mid','Mid-dark','Darkest'][i]}"></i>`).join('')}</div><p>All four are colors. But they also create a value path from lighter to darker—without adding black.</p><div class="value-arrow">LIGHTER <span>→</span> DARKER</div></div></div>`,buttons());bindNav();save()}
function shapeHTML(shape,prefix,colors=['#e7e5e9','#aaa8ad','#5c5961']){return `<div class="shape-area"><div class="shape ${shape}">${[0,1,2].map(i=>`<div class="zone z${i+1}" data-zone="${i}" style="--fill:${state.paint[`${prefix}-${shape}-${i}`]||state.paint[`${prefix}-${i}`]||colors[i]}"></div>`).join('')}<div class="cast-shadow" style="--shadow-color:${state.paint[`${prefix}-${shape}-shadow`]||'#a9a5ae'}"></div></div></div>`}
function forms(){const f=families[state.family],shape=['cube','sphere','cylinder'][state.shape],prefix='neighbor',done=['0','1','2'].every(i=>state.paint[`${prefix}-${shape}-${i}`]);shell('Paint light with neighbors',`Do not add black or white. Use one color family from light to dark. ${state.shape+1} of 3: ${shape}.`,`<div class="panel"><aside class="lesson-note"><div class="eyebrow">Tap or drag</div><h3>${shape[0].toUpperCase()+shape.slice(1)}</h3><p>Choose a color, then place it on the matching light, middle or dark area.</p><div class="chip-row">${[f.colors[0],f.colors[2],f.colors[3]].map((c,i)=>`<label class="color-choice"><button class="chip ${selected===c?'selected':''}" draggable="true" data-color="${c}" style="--c:${c}" aria-label="${['Light color','Middle color','Dark color'][i]}"></button><small>${['LIGHT','MIDDLE','DARK'][i]}</small></label>`).join('')}</div>${processVideo('neighbor-process.mp4','neighbors-demo.jpg','Watch neighboring hues replace gray while the same light-to-dark structure stays visible')}</aside>${shapeHTML(shape,prefix)}</div>`,`${state.page?'<button class="btn secondary" data-back>Back</button>':''}${state.shape?'<button class="btn secondary" data-prevshape>Previous shape</button>':''}<button class="btn" data-shape ${done?'':'disabled'}>${state.shape<2?'Next shape':'See the classroom'} →</button>`);bindPaint(prefix,done);document.querySelector('[data-shape]').onclick=()=>{selected=null;if(state.shape<2){state.shape++;save();render()}else next()};const p=document.querySelector('[data-prevshape]');if(p)p.onclick=()=>{selected=null;state.shape--;save();render()}}
function pairs(){const names=[['Yellow','Violet',2,8],['Red','Green',0,6],['Blue','Orange',7,1]];shell('Find the color across the wheel','Complementary colors sit opposite each other. Find all three pairs.',`<div class="pairs">${names.map((p,i)=>`<div class="pair ${state.pairs.includes(i)?'found':''}" data-pair="${i}"><b>${p[0]} + ${p[1]}</b><div class="pair-dots"><button data-side="0" style="--c:${COLORS[p[2]]}"></button><button data-side="1" style="--c:${COLORS[p[3]]}"></button></div></div>`).join('')}</div>`,buttons(state.pairs.length===3));bindNav();document.querySelectorAll('[data-pair]').forEach(card=>card.onclick=()=>{let i=+card.dataset.pair;if(!state.pairs.includes(i))state.pairs.push(i);save();tone(470+i*80);render()})}
function environment(){const shapes=['cube','sphere','cylinder'],shape=shapes[state.shape],pairs=[['#f1cf47','#7452aa'],['#e65754','#46a464'],['#4078c5','#ef873c']],pair=pairs[state.shape],prefix='comp',done=!!state.paint[`${prefix}-${shape}-shadow`];shell('Let the environment enter the form',`Keep the object’s neighbor colors. Add its opposite only where the environment reflects or casts a shadow. ${state.shape+1} of 3: ${shape}.`,`<div class="panel"><aside class="lesson-note"><div class="eyebrow">Local color + environment</div><h3>One careful accent</h3><p>Drag the complementary color into the cast shadow. It should support the form, not replace it.</p><div class="chip-row"><label class="color-choice"><button class="chip" data-color="${pair[1]}" draggable="true" style="--c:${pair[1]}" aria-label="Environmental complement"></button><small>ENVIRONMENT</small></label></div>${processVideo('complement-process.mp4','complements-demo.jpg','Watch complementary color enter reflected light and cast shadow without replacing the object color')}</aside>${shapeHTML(shape,prefix,[pair[0],pair[0],pair[0]])}</div>`,`${state.page?'<button class="btn secondary" data-back>Back</button>':''}${state.shape?'<button class="btn secondary" data-prevshape>Previous shape</button>':''}<button class="btn" data-shape ${done?'':'disabled'}>${state.shape<2?'Next shape':'See the classroom'} →</button>`);selected=pair[1];bindPaint(prefix,done,true);document.querySelector('[data-shape]').onclick=()=>{if(state.shape<2){state.shape++;save();render()}else next()};const p=document.querySelector('[data-prevshape]');if(p)p.onclick=()=>{state.shape--;save();render()}}
function bindPaint(prefix,already,shadowOnly=false){document.querySelectorAll('[data-color]').forEach(c=>{c.onclick=()=>{selected=c.dataset.color;render()};c.ondragstart=e=>{selected=c.dataset.color;e.dataTransfer.setData('text/plain',selected)}});const shape=['cube','sphere','cylinder'][state.shape]||'cube';document.querySelectorAll('.zone,.cast-shadow').forEach((z,i)=>{z.ondragover=e=>e.preventDefault();const apply=()=>{if(!selected)return say('Choose a paint color first.');if(shadowOnly&&z.classList.contains('zone'))return say('Keep the object color. Paint the cast shadow.');const choices=[...document.querySelectorAll('[data-color]')],choice=Math.max(0,choices.findIndex(c=>c.dataset.color===selected));const key=z.classList.contains('cast-shadow')?`${prefix}-${shape}-shadow`:`${prefix}-${shape}-${choice}`;state.paint[key]=selected;save();tone(390+choice*55);render()};z.onclick=apply;z.ondrop=e=>{e.preventDefault();selected=e.dataTransfer.getData('text/plain')||selected;apply()}});bindNav()}
function classroom(){const isNeighbors=C.mode==='neighbors';shell('See it happen on real paper','This is the same sequence from the Saturday class: grayscale, neighbor color, then complementary environment.',`<div class="reference"><img src="../color-practice-shapes/assets/classroom-outcome.jpg" alt="Teacher’s finished cube, sphere and cylinder studies"><div class="reference-copy"><div class="eyebrow">Real classroom reference</div><h3>${isNeighbors?'Color can carry value.':'The environment changes color.'}</h3><p>${C.classroom}</p>${processVideo(isNeighbors?'neighbor-process.mp4':'complement-process.mp4',isNeighbors?'neighbors-demo.jpg':'complements-demo.jpg',isNeighbors?'Review the neighbor-color painting process':'Review the complementary environment process')}</div></div>`,buttons(true,'Finish the lesson'));bindNav()}
function finish(){state.complete=true;save();localStorage.setItem(C.completeKey,'true');shell('You used color to build form',C.finish,`<div class="finish"><img src="../color-practice-shapes/assets/classroom-outcome.jpg" alt="Completed classroom studies"><div><div class="eyebrow">Lesson complete ✓</div><h3>${C.reward}</h3><p>${C.finish}</p><div class="actions"><button class="btn secondary" data-replay>Play again</button><a class="btn" href="${C.nextHref}">${C.nextLabel} →</a></div></div></div>`,'');document.querySelector('[data-replay]').onclick=()=>{state={page:0,family:0,shape:0,paint:{},pairs:[],complete:true};save();render()}}
function render(){if(state.page===0)return intro();if(C.mode==='neighbors'){if(state.page===1)return valueBridge();if(state.page===2)return family();if(state.page===3)return forms();if(state.page===4)return classroom();return finish()}if(state.page===1)return pairs();if(state.page===2)return environment();if(state.page===3)return classroom();return finish()}
render();
})();
