(()=>{
const C=window.COLOR_SHAPE_LESSON,root=document.querySelector('#stage'),bar=document.querySelector('.progress i'),toast=document.querySelector('.toast');
const GRAYS=['#f4f3f1','#d6d4d2','#aaa7a6','#716f72','#343238'];
const FAMILIES=[{name:'Yellow → Red',colors:['#f5d64a','#f1b33f','#ed843e','#df5d44','#c74648']},{name:'Yellow → Green',colors:['#f4d84d','#bfd055','#83b957','#4b9760','#316f58']},{name:'Blue → Green',colors:['#78c5d0','#4eacb5','#338d98','#2e747f','#2d5866']},{name:'Blue → Violet',colors:['#73b8d8','#5d91c5','#5872b0','#604f96','#503b75']},{name:'Red → Violet',colors:['#eb7771','#d75e6c','#ba4f78','#93467f','#683d75']}];
const SHAPES=['cube','sphere','cylinder'],zoneCount=s=>s==='sphere'?5:3;
let old=JSON.parse(localStorage.getItem(C.key)||'null'),state=old&&old.neighborVersion===3?old:{neighborVersion:3,page:0,family:0,shape:0,paint:{},checked:{},complete:!!old?.complete},selected=null,sound=false;
const save=()=>localStorage.setItem(C.key,JSON.stringify(state)),say=t=>{toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)};
function tone(n=440){if(!sound)return;const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=n;g.gain.setValueAtTime(.03,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.2);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.21)}
document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'Sound on':'Sound off';tone()};
function shell(title,sub,body,actions=''){bar.style.width=`${(state.page+1)/6*100}%`;root.innerHTML=`<section class="page neighbor-page"><header class="heading"><div class="eyebrow">${C.kicker}</div><h2>${title}</h2><p>${sub}</p></header><div class="workspace">${body}</div><footer class="actions">${actions}</footer></section>`}
const back=()=>`<button class="btn secondary" data-back>Back</button>`,next=label=>`${back()}<button class="btn" data-next>${label} →</button>`;
function go(p){state.page=Math.max(0,Math.min(5,p));selected=null;save();render()}function nav(){document.querySelector('[data-back]')?.addEventListener('click',()=>go(state.page-1));document.querySelector('[data-next]')?.addEventListener('click',()=>go(state.page+1))}
const rail=(colors,labels=false)=>`<div class="value-rail">${colors.map((c,i)=>`<i style="--c:${c};--delay:${i}">${labels?`<span>${['Lightest','Light','Middle','Dark','Darkest'][i]}</span>`:''}</i>`).join('')}</div>`;
function intro(){shell('Can color carry light?','Watch value move from light to dark. Then use color to do the same job.',`<div class="neighbor-intro"><div class="question-mark">?</div><div class="intro-rails">${rail(GRAYS)}${rail(FAMILIES[0].colors)}</div><div class="intro-copy"><b>Same light.</b><span>Two visual languages.</span></div></div>`,`<button class="btn" data-next>Watch value change →</button>`);document.querySelector('[data-next]').onclick=()=>go(1)}
function valueDemo(){shell('What is value?','You do not need to click each block. Watch: value is simply how light or dark something appears.',`<div class="auto-demo value-auto"><div class="sun-cue"><span>LIGHT</span><i></i><span>SHADOW</span></div>${rail(GRAYS,true)}<div class="demo-caption"><b>Light becomes shadow one step at a time.</b><span>No color has been added yet.</span></div></div>`,next('Now watch color do it'));nav()}
function familyDemo(){shell('Color already has value','Watch each neighboring-color family line up with the same light-to-dark path—without black or white.',`<div class="family-lab auto-family"><div class="rail-caption"><span>HIGHER VALUE</span><b>Monochrome reference</b><span>LOWER VALUE</span></div>${rail(GRAYS,true)}<div class="family-stack">${FAMILIES.map((f,i)=>`<button class="family-row ${i===state.family?'chosen':''}" data-family="${i}" style="--delay:${i}"><b>${f.name}</b>${rail(f.colors)}<small>${i===state.family?'Your practice family ✓':'Choose for your practice'}</small></button>`).join('')}</div><p class="demo-caption"><b>All five families demonstrate automatically.</b><span>Choose one family only because you will paint with it next.</span></p></div>`,next('See color match value'));nav();document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{state.family=+b.dataset.family;save();tone(450+state.family*40);render()})}
function mappingDemo(){const f=FAMILIES[state.family];shell('Two visual languages, one value path','Watch each color move to the matching gray. Lightest meets lightest; darkest meets darkest.',`<div class="mapping-lab mapping-auto"><div class="family-tabs">${FAMILIES.map((x,i)=>`<button class="${i===state.family?'on':''}" data-family="${i}">${x.name}</button>`).join('')}</div><div class="mapping-board"><div class="map-row">${GRAYS.map((c,i)=>`<span style="--c:${c}"><i></i><small>${['Highest','High','Middle','Low','Lowest'][i]}</small></span>`).join('')}</div><div class="auto-map-lines">${GRAYS.map((_,i)=>`<i style="--delay:${i}">↑</i>`).join('')}</div><div class="map-row">${f.colors.map((c,i)=>`<span class="travel-swatch" style="--c:${c};--delay:${i}"><i></i><small>${['Lightest','Light','Middle','Dark','Darkest'][i]}</small></span>`).join('')}</div></div><p class="mapping-prompt">The movement is the explanation. Your first hands-on decision comes next.</p></div>`,next('Paint a form yourself'));nav();document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{state.family=+b.dataset.family;save();render()})}
function sphereSvg(colors,mode){const paths=['M120 20A100 100 0 0 0 120 220C80 196 72 48 120 20Z','M120 20C72 48 80 196 120 220C150 192 151 50 120 20Z','M120 20C151 50 150 192 120 220C174 194 181 51 120 20Z','M120 20C181 51 174 194 120 220C207 178 210 66 120 20Z','M120 20C210 66 207 178 120 220A100 100 0 0 0 120 20Z'];return `<div class="study-shape sphere ${mode}"><svg viewBox="0 0 240 240">${paths.map((d,i)=>`<path data-zone="${i}" d="${d}" style="--fill:${colors[i]||'#f4f2ef'}"/>`).join('')}</svg><div class="study-shadow" style="--shadow:${colors[4]||'#777'}"></div></div>`}
function shapeMarkup(shape,colors,mode='reference'){if(shape==='sphere')return sphereSvg(colors,mode);const n=zoneCount(shape);return `<div class="study-shape ${shape} ${mode}">${Array.from({length:n},(_,i)=>`<div class="paint-zone z${i+1}" data-zone="${i}" style="--fill:${colors[i]||'#f4f2ef'}"></div>`).join('')}<div class="study-shadow" style="--shadow:${colors[n-1]||'#777'}"></div></div>`}
function practice(){const shape=SHAPES[state.shape],f=FAMILIES[state.family],n=zoneCount(shape),idx=n===5?[0,1,2,3,4]:[0,2,4],key=i=>`${shape}-${i}`,paint=idx.map((_,i)=>state.paint[key(i)]),done=paint.every(v=>v!==undefined),checked=state.checked[shape],correct=done&&paint.filter((v,i)=>v===idx[i]).length,labels=n===5?['HIGHLIGHT','LIGHT','MIDDLE','SHADOW','DEEPEST']:['LIGHT AREA','MIDDLE AREA','DARK AREA'];
shell('Paint light with color',`Choose a paint, then drag or tap it onto one part of the ${shape}.`, `<div class="form-practice"><div class="action-demo paint-demo"><b>WATCH ONCE</b><span><i>1</i> Choose a swatch</span><strong>→</strong><span><i>2</i> Drag it onto a form area</span></div><div class="practice-toolbar"><div><div class="eyebrow">YOUR FAMILY</div><h3>${f.name}</h3></div><div class="practice-palette">${f.colors.map((c,i)=>`<button draggable="true" data-paint="${i}" class="${selected===i?'on':''}" style="--c:${c}"><i></i><small>${['Lightest','Light','Middle','Dark','Darkest'][i]}</small></button>`).join('')}</div></div><div class="compare-forms"><section><b>VALUE GUIDE</b><p>This form is already solved for you.</p><div class="shape-paper">${shapeMarkup(shape,n===5?GRAYS:[GRAYS[0],GRAYS[2],GRAYS[4]])}</div></section><div class="compare-arrow">→</div><section class="learner-study"><b>YOUR COLOR STUDY</b><p>${selected==null?'Choose one swatch above.':'Now place it where that value belongs.'}</p><div class="shape-paper learner-paper">${shapeMarkup(shape,paint.map(v=>v===undefined?'':f.colors[v]),'learner')}</div><div class="surface-guides">${labels.map((x,i)=>`<button data-zone="${i}" class="${paint[i]!==undefined?'painted':''}" style="--fill:${paint[i]===undefined?'#ddd':f.colors[paint[i]]}">${x}</button>`).join('')}</div></section></div>${done&&!checked?`<div class="practice-check"><button class="btn" data-check>Done · Check my light</button></div>`:''}${checked?`<div class="learning-analysis ${correct===n?'is-clear':'needs-adjustment'}"><div><b>${correct===n?'Your value path is clear.':'Your form is painted—now compare the value choices.'}</b><span>${correct===n?'Light moves gradually into shadow.':`${correct} of ${n} areas follow the recommended order. Move lighter hues toward light and darker hues toward shadow.`}</span></div><div class="recommended-study"><small>RECOMMENDED PLACEMENT</small>${shapeMarkup(shape,idx.map(i=>f.colors[i]),'resolved')}</div></div>`:''}</div>`,`${back()}${checked?`<button class="btn secondary" data-adjust>Adjust mine</button><button class="btn" data-shape-next>${state.shape<2?'Next form':'Finish practice'} →</button>`:''}`);
document.querySelector('[data-back]').onclick=()=>go(3);document.querySelectorAll('[data-paint]').forEach(b=>{b.onclick=()=>{selected=+b.dataset.paint;render()};b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.paint)});const apply=(z,v=selected)=>{if(v==null||v==='')return say('Choose a paint first.');state.paint[key(+z.dataset.zone)]=+v;state.checked[shape]=false;save();tone(480);render()};document.querySelectorAll('.learner-study [data-zone]').forEach(z=>{z.onclick=()=>apply(z);z.ondragover=e=>e.preventDefault();z.ondrop=e=>{e.preventDefault();apply(z,e.dataTransfer.getData('text/plain'))}});document.querySelector('[data-check]')?.addEventListener('click',()=>{state.checked[shape]=true;save();render()});document.querySelector('[data-adjust]')?.addEventListener('click',()=>{state.checked[shape]=false;save();render()});document.querySelector('[data-shape-next]')?.addEventListener('click',()=>{if(state.shape<2){state.shape++;selected=null;save();render()}else go(5)})}
function finish(){state.complete=true;localStorage.setItem(C.completeKey,'true');save();const f=FAMILIES[state.family];shell('You made light with color',`You used the value already inside ${f.name} to turn three forms.`, `<div class="neighbor-finish"><div class="finish-gallery">${SHAPES.map(s=>{const ix=zoneCount(s)===5?[0,1,2,3,4]:[0,2,4];return `<div class="shape-paper">${shapeMarkup(s,ix.map((_,i)=>f.colors[state.paint[`${s}-${i}`]??ix[i]]),'resolved')}</div>`}).join('')}</div><div><div class="eyebrow">LESSON COMPLETE ✓</div><h3>Color can carry light.</h3><p>The full classroom reference appears at the end of Complementary Colors.</p></div></div>`,`<button class="btn secondary" data-replay>Practice again</button><a class="btn" href="${C.nextHref}">${C.nextLabel} →</a>`);document.querySelector('[data-replay]').onclick=()=>{state={neighborVersion:3,page:0,family:0,shape:0,paint:{},checked:{},complete:true};save();render()}}
function render(){[intro,valueDemo,familyDemo,mappingDemo,practice,finish][state.page]()};render();
})();
