from pathlib import Path
import base64,json
root=Path(__file__).resolve().parents[1];out=root/'assets/sketch-support/balloon'
items=[(45,'Find the tilt before the outline','Compare the guide lines before adding detail.','The teacher is finding the direction and overall shape before adding any shading. Notice the tilted guide lines. Compare their angles, and keep your construction marks light.', '<path d="M550 80 L725 585 M385 326 L910 150" stroke="#1262ff" stroke-width="5" stroke-dasharray="14 10" fill="none"/><path d="M1040 100 Q980 90 890 145" class="arrow"/>'),(150,'Turn corners into soft curves','Foil has volume: let the edges bend.','Pause to compare the outline with the finished balloon beside the video. The edges bend inward between the points. Use gentle curves instead of making every edge a straight line.', '<path d="M550 75 Q480 260 380 326" stroke="#1262ff" stroke-width="6" fill="none"/><path d="M190 410 Q220 310 402 300" class="arrow"/>'),(270,'Separate the seam from the outline','Look for the narrow rim inside the edge.','Look closely at the rim just inside the balloon outline. This seam is separate from the outer edge. Keep that narrow space visible; it will help the balloon feel like inflated foil.', '<path d="M930 180 Q905 290 875 355" stroke="#1262ff" stroke-width="6" fill="none"/><path d="M1115 350 Q1040 325 910 305" class="arrow"/>'),(330,'Let folds turn toward the centre','Follow each fold’s direction.','These small inward curves describe folds in the foil. Notice how they turn from the rim toward the centre. Draw the folds you can see, keeping them light before the shading begins.', '<ellipse cx="600" cy="320" rx="155" ry="115" stroke="#1262ff" stroke-width="5" stroke-dasharray="12 9" fill="#a78bfa22"/><path d="M230 420 Q280 340 430 325" class="arrow"/>')]
pauses=[]
for i,(t,title,short,text,marks) in enumerate(items):
 data=base64.b64encode((out/f'{t}.jpg').read_bytes()).decode()
 svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720"><defs><marker id="tip" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M1 1 L8 5 L1 9" fill="none" stroke="#00d5b0" stroke-width="2"/></marker><style>.arrow{{fill:none;stroke:#00d5b0;stroke-width:5;marker-end:url(#tip)}}</style></defs><image href="data:image/jpeg;base64,{data}" width="1280" height="720"/>{marks}<rect x="25" y="22" width="420" height="116" rx="16" fill="#ffffffee"/><rect x="25" y="22" width="7" height="116" rx="3" fill="#a78bfa"/><text x="48" y="56" font-family="Arial" font-size="15" fill="#7954a7" font-weight="bold">LOOK CLOSELY · {i+1:02}</text><text x="48" y="88" font-family="Arial" font-size="21" fill="#273044" font-weight="bold">{title}</text><text x="48" y="117" font-family="Arial" font-size="16" fill="#506175">{short}</text></svg>'''
 (out/f'key-{i+1}.svg').write_text(svg)
 pauses.append(dict(time=t,duration=60,title=title,shortPrompt=short,text=text,voiceoverEn=text,image=f'../../assets/sketch-support/balloon/key-{i+1}.svg',lesson='still-life-1a-star-balloon-structure',uid='6bb909b0169fb6e58f666c8e2abb6ad2',index=i,map='VIDEO_PAUSES'))
p=root/'lessons/still-life-1a-star-balloon-structure/index.html';s=p.read_text().replace('const VIDEO_PAUSES = {};','const VIDEO_PAUSES = '+json.dumps({'6bb909b0169fb6e58f666c8e2abb6ad2':[{k:v for k,v in item.items() if k not in ['lesson','uid','index','map']} for item in pauses]},indent=2)+';');p.write_text(s)
p=root/'assets/sketch-support/pause-audit.json';existing=json.loads(p.read_text());existing=[p for p in existing if p['lesson']!='still-life-1a-star-balloon-structure'];p.write_text(json.dumps(existing+pauses,indent=2))
