(()=>{
const C=window.COLOR_SHAPE_LESSON,root=document.querySelector('#stage'),bar=document.querySelector('.progress i'),toast=document.querySelector('.toast');
const PAIRS=[{name:'Yellow + Violet',baseName:'Yellow',oppositeName:'Violet',base:'#f0ce43',opposite:'#704e9d'},{name:'Red + Green',baseName:'Red',oppositeName:'Green',base:'#df5b55',opposite:'#419362'},{name:'Blue + Orange',baseName:'Blue',oppositeName:'Orange',base:'#477ac3',opposite:'#e88843'}],NAMES=['LOCAL','LIGHT','LIGHT–MID','MID–SHADOW','REFLECTED','DEEPEST'];
let old=JSON.parse(localStorage.getItem(C.key)||'null'),state=old&&old.version===3?old:{version:3,page:0,pair:0,paint:{},checked:false,complete:!!old?.complete},selected=null,sound=false;
const save=()=>localStorage.setItem(C.key,JSON.stringify(state)),say=t=>{toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)};
function tone(n=440){if(!sound)return;const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=n;g.gain.setValueAtTime(.03,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.2);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.21)}
document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'Sound on':'Sound off';tone()};
function shell(title,sub,body,actions=''){bar.style.width=`${(state.page+1)/7*100}%`;root.innerHTML=`<section class="page neighbor-page complement-page"><header class="heading"><div class="eyebrow">${C.kicker}</div><h2>${title}</h2><p>${sub}</p></header><div class="workspace">${body}</div><footer class="actions">${actions}</footer></section>`}
const back=()=>`<button class="btn secondary" data-back>Back</button>`,next=label=>`${back()}<button class="btn" data-next>${label} →</button>`;function go(p){state.page=Math.max(0,Math.min(6,p));selected=null;save();render()}function nav(){const b=document.querySelector('[data-back]'),n=document.querySelector('[data-next]');if(b)b.onclick=()=>go(state.page-1);if(n)n.onclick=()=>go(state.page+1)}
function mixes(p){return Array.from({length:6},(_,i)=>`color-mix(in srgb, ${p.base} ${100-i*12}%, ${p.opposite})`)}
const PATHS=['M120 20A100 100 0 0 0 120 220C82 196 75 48 120 20Z','M120 20C75 48 82 196 120 220C148 194 151 48 120 20Z','M120 20C151 48 148 194 120 220C172 196 180 49 120 20Z','M120 20C180 49 172 196 120 220C201 184 207 61 120 20Z','M120 20C207 61 201 184 120 220C222 163 222 78 120 20Z','M120 20C222 78 222 163 120 220A100 100 0 0 0 120 20Z'];
function sphere(colors,interactive=false){return `<div class="comp-sphere-svg ${interactive?'interactive':''}"><svg viewBox="0 0 240 240">${PATHS.map((d,i)=>`<path data-layer="${i}" d="${d}" style="--fill:${colors[i]||'#f5f2ef'}"/>`).join('')}</svg><i class="comp-reflection"></i><i class="comp-shadow" style="--shadow:${colors[5]||'#777'}"></i></div>`}
function intro(){shell('What can an opposite color do?','A complement can soften, turn and connect a form to its environment.',`<div class="complement-hero">${PAIRS.map(p=>`<div class="opposite-orbit"><i style="--c:${p.base}"></i><span>↔</span><i style="--c:${p.opposite}"></i><b>${p.name}</b></div>`).join('')}</div>`,`<button class="btn" data-next>Watch the opposites →</button>`);document.querySelector('[data-next]').onclick=()=>go(1)}
function pairsDemo(){shell('Colors across the wheel','Watch the three complementary pairs wake up. You do not need to tap every card.',`<div class="complement-pairs auto-pairs">${PAIRS.map((p,i)=>`<button data-pair="${i}" class="${i===state.pair?'chosen':''}" style="--delay:${i}"><span style="--a:${p.base};--b:${p.opposite}"></span><b>${p.name}</b><small>${i===state.pair?'Your practice pair ✓':'Choose for your practice'}</small></button>`).join('')}</div>`,next('Watch them blend'));nav();document.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{state.pair=+b.dataset.pair;state.paint={};state.checked=false;save();render()})}
function blendDemo(){const p=PAIRS[state.pair];shell('Let the opposite enter gradually','Watch the complement flow through six connected mixtures. It is never a hard half-and-half split.',`<div class="blend-lab auto-blend"><div class="family-tabs">${PAIRS.map((x,i)=>`<button data-pair="${i}" class="${i===state.pair?'on':''}">${x.name}</button>`).join('')}</div><div class="blend-scale">${mixes(p).map((c,i)=>`<div style="--blend:${c};--delay:${i}"><i></i><b>${NAMES[i]}</b><small>${i===0?p.baseName:i===5?`Mostly ${p.oppositeName}`:`More ${p.oppositeName}`}</small></div>`).join('')}</div><p class="mapping-prompt">The animation demonstrates the mixing. Your decision comes next: where should each mixture live on the form?</p></div>`,next('Paint reflected light'));nav();document.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{state.pair=+b.dataset.pair;state.paint={};state.checked=false;save();render()})}
function paint(){const p=PAIRS[state.pair],palette=mixes(p),colors=Array.from({length:6},(_,i)=>state.paint[i]===undefined?'':palette[state.paint[i]]),done=colors.every(Boolean);shell('Paint the environment into the form','Use all six mixtures. Decide where local color, turning shadow and reflected complement belong.',`<div class="form-practice"><div class="action-demo paint-demo"><b>WATCH ONCE</b><span><i>1</i> Choose a blend</span><strong>→</strong><span><i>2</i> Drag it onto a curved layer</span></div><div class="comp-palette">${palette.map((c,i)=>`<button draggable="true" data-color="${i}" class="${selected===i?'on':''}" style="--c:${c}"><i></i><small>${NAMES[i]}</small></button>`).join('')}</div><div class="compare-forms"><section><b>MONOCHROME GUIDE</b><p>Six curved value areas turn a real sphere.</p><div class="shape-paper">${sphere(['#f5f4f2','#dddcd9','#bcb9b8','#918e90','#666367','#36343a'])}</div></section><div class="compare-arrow">→</div><section class="learner-study"><b>YOUR WATERCOLOR STUDY</b><p>${selected==null?'Choose a mixture above.':'Place it where you think it belongs.'}</p><div class="shape-paper">${sphere(colors,true)}</div><div class="comp-layer-guides">${NAMES.map((n,i)=>`<button data-layer-guide="${i}" class="${colors[i]?'painted':''}" style="--fill:${colors[i]||'#ddd'}">${n}</button>`).join('')}</div></section></div>${done?`<div class="practice-check"><button class="btn" data-check>Done · Analyze my choices</button></div>`:''}</div>`,back());document.querySelector('[data-back]').onclick=()=>go(2);document.querySelectorAll('[data-color]').forEach(b=>{b.onclick=()=>{selected=+b.dataset.color;render()};b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.color)});const apply=(b,v=selected)=>{if(v==null||v==='')return say('Choose a mixture first.');state.paint[+(b.dataset.layerGuide??b.dataset.layer)]=+v;state.checked=false;save();tone(480);render()};document.querySelectorAll('.interactive [data-layer], [data-layer-guide]').forEach(b=>{b.onclick=()=>apply(b);b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();apply(b,e.dataTransfer.getData('text/plain'))}});const check=document.querySelector('[data-check]');if(check)check.onclick=()=>{state.checked=true;save();go(4)}}
function analysis(){const p=PAIRS[state.pair],palette=mixes(p),chosen=Array.from({length:6},(_,i)=>palette[state.paint[i]]),score=Array.from({length:6},(_,i)=>state.paint[i]===i).filter(Boolean).length,perfect=score===6;shell('Read what your color is doing',perfect?'Your placement moves clearly from local color into reflected complementary shadow.':'Compare your placement with the recommended watercolor relationship.',`<div class="analysis-compare"><section><div class="eyebrow">YOUR CHOICES · ${score}/6 IN THE RECOMMENDED VALUE ORDER</div>${sphere(chosen)}</section><section><div class="eyebrow">RECOMMENDED PLACEMENT</div>${sphere(palette)}</section></div><div class="placement-notes"><b>${perfect?'The sphere turns convincingly.':'What to adjust'}</b><ol><li>Keep the local color strongest in the highlight and light.</li><li>Let the complement enter gradually through the middle.</li><li>Use the strongest complement in reflected light, deep shadow and the cast shadow—not in the highlight.</li></ol><p>There can be many beautiful results, but the value order must still make the light readable.</p></div>`,`<button class="btn secondary" data-adjust>Adjust my sphere</button><button class="btn" data-next>See the classroom process →</button>`);document.querySelector('[data-adjust]').onclick=()=>go(3);document.querySelector('[data-next]').onclick=()=>go(5)}
function teacher(){shell('Now watch the whole process on paper','This silent classroom demonstration is a reference—not a standard answer. Look for the same gradual value and complementary-color decisions.',`<div class="teacher-reference"><div class="teacher-video"><video src="../color-practice-shapes/assets/classroom-process-clean.mp4" muted controls playsinline preload="metadata"></video><span>Full classroom process · cleaned and muted</span></div><div class="reference-note"><div class="eyebrow">LOOK FOR</div><ol><li>How value turns the forms</li><li>Neighboring hues replacing gray</li><li>Complement entering gradually</li><li>Environmental color inside shadow</li></ol></div></div>`,next('Finish the lesson'));nav()}
function finish(){state.complete=true;localStorage.setItem(C.completeKey,'true');save();const p=PAIRS[state.pair],palette=mixes(p);shell('You gave color an environment','You used a complement to turn form, reflect light and connect the shadow to the space around it.',`<div class="neighbor-finish"><div class="shape-paper">${sphere(palette)}</div><div><div class="eyebrow">LESSON COMPLETE ✓</div><h3>Opposites can belong together.</h3><p>You blended them instead of separating them.</p></div></div>`,`<button class="btn secondary" data-replay>Practice again</button><a class="btn" href="${C.nextHref}">${C.nextLabel} →</a>`);document.querySelector('[data-replay]').onclick=()=>{state={version:3,page:0,pair:0,paint:{},checked:false,complete:true};save();render()}}
function render(){[intro,pairsDemo,blendDemo,paint,analysis,teacher,finish][state.page]()};render();
})();
