(()=>{
const C=window.COLOR_SHAPE_LESSON,root=document.querySelector('#stage'),bar=document.querySelector('.progress i'),toast=document.querySelector('.toast');
const PAIRS=[
 {name:'Yellow + Violet',baseName:'Yellow',oppositeName:'Violet',base:'#f0ce43',opposite:'#704e9d'},
 {name:'Red + Green',baseName:'Red',oppositeName:'Green',base:'#df5b55',opposite:'#419362'},
 {name:'Blue + Orange',baseName:'Blue',oppositeName:'Orange',base:'#477ac3',opposite:'#e88843'}
];
let stored=JSON.parse(localStorage.getItem(C.key)||'null');
let state=stored&&stored.version===2?stored:{version:2,page:0,found:[],pair:0,mixed:[],paint:{},refined:false,complete:!!stored?.complete};
let selected=null,sound=false;
const save=()=>localStorage.setItem(C.key,JSON.stringify(state));
const say=t=>{toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)};
function tone(n=440){if(!sound)return;const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=n;g.gain.setValueAtTime(.03,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.2);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.21)}
document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'Sound on':'Sound off';tone()};
function shell(title,sub,body,actions=''){bar.style.width=`${(state.page+1)/7*100}%`;root.innerHTML=`<section class="page neighbor-page complement-page"><header class="heading"><div class="eyebrow">${C.kicker}</div><h2>${title}</h2><p>${sub}</p></header><div class="workspace">${body}</div><footer class="actions">${actions}</footer></section>`}
const back=()=>`<button class="btn secondary" data-back>Back</button>`;
const next=(enabled,label)=>`${back()}<button class="btn" data-next ${enabled?'':'disabled'}>${label} →</button>`;
function go(p){state.page=Math.max(0,Math.min(6,p));selected=null;save();render()}
function nav(){document.querySelector('[data-back]')?.addEventListener('click',()=>go(state.page-1));document.querySelector('[data-next]')?.addEventListener('click',()=>go(state.page+1))}
function intro(){shell('What can an opposite color do?','A complementary color does more than create contrast. In watercolor, it can soften, turn and connect a form to its environment.',`<div class="complement-hero">${PAIRS.map(p=>`<div class="opposite-orbit"><i style="--c:${p.base}"></i><span>↔</span><i style="--c:${p.opposite}"></i><b>${p.name}</b></div>`).join('')}</div>`,`<button class="btn" data-next>Find the three opposites →</button>`);document.querySelector('[data-next]').onclick=()=>go(1)}
function pairs(){const done=state.found.length===3;shell('Find the colors across the wheel','Tap each pair to wake it up. These opposites will become reflected light and shadow.',`<div class="complement-pairs">${PAIRS.map((p,i)=>`<button data-pair="${i}" class="${state.found.includes(i)?'found':''}"><span style="--a:${p.base};--b:${p.opposite}"></span><b>${p.name}</b><small>${state.found.includes(i)?'Opposites found ✓':'Tap to compare'}</small></button>`).join('')}</div>`,next(done,'Build a blended scale'));nav();document.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{const i=+b.dataset.pair;if(!state.found.includes(i))state.found.push(i);state.pair=i;save();tone(420+i*90);render()})}
function blend(){const p=PAIRS[state.pair],done=state.mixed.length===6,instructions=[`Begin with ${p.baseName}`,`Add a trace of ${p.oppositeName}`,`Add a little more ${p.oppositeName}`,`Let both colors meet`,`Let ${p.oppositeName} begin to lead`,`Mostly ${p.oppositeName}; some ${p.baseName} remains`];shell('Let the opposite enter gradually','Each band begins with the local color. Add more of its complement as you move toward shadow—never as a hard split.',`<div class="blend-lab"><div class="action-demo"><b>HOW TO BLEND</b><span><i>1</i> Choose a pair</span><strong>→</strong><span><i>2</i> Tap each band from 1 to 6</span><strong>→</strong><span><i>3</i> Watch the edges flow together</span></div><div class="family-tabs">${PAIRS.map((x,i)=>`<button data-choose-pair="${i}" class="${i===state.pair?'on':''}">${x.name}</button>`).join('')}</div><div class="blend-scale">${Array.from({length:6},(_,i)=>`<button data-band="${i}" class="${state.mixed.includes(i)?'mixed':''}" style="--base:${p.base};--opposite:${p.opposite};--blend:color-mix(in srgb,${p.base} ${100-i*12}%,${p.opposite})"><i></i><b>${i===0?'LOCAL COLOR':i===5?'DEEPEST BLEND':`BLEND ${i+1}`}</b><small>${state.mixed.includes(i)?'Watercolor blended ✓':instructions[i]}</small></button>`).join('')}</div><p class="mapping-prompt">${done?'Six connected mixtures: the complement now moves gradually through the form.':'Start at the local color and move one band at a time.'}</p></div>`,next(done,'Paint reflected light'));nav();document.querySelectorAll('[data-choose-pair]').forEach(b=>b.onclick=()=>{state.pair=+b.dataset.choosePair;state.mixed=[];save();render()});document.querySelectorAll('[data-band]').forEach(b=>b.onclick=()=>{const i=+b.dataset.band;if(i>0&&!state.mixed.includes(i-1))return say('Blend the previous band first.');if(!state.mixed.includes(i))state.mixed.push(i);save();tone(560-i*38);render()})}
function mixes(p){return Array.from({length:6},(_,i)=>`color-mix(in srgb, ${p.base} ${100-i*12}%, ${p.opposite})`)}
function sphere(colors,interactive=false){return `<div class="comp-sphere ${interactive?'interactive':''}">${colors.map((c,i)=>`<button data-layer="${i}" style="--fill:${c||'#f5f2ef'}" aria-label="Sphere layer ${i+1}"></button>`).join('')}<i class="comp-reflection"></i><i class="comp-shadow" style="--shadow:${colors[5]||'#777'}"></i></div>`}
function paint(){const p=PAIRS[state.pair],palette=mixes(p),colors=Array.from({length:6},(_,i)=>state.paint[i]),done=colors.every(Boolean),names=['LOCAL','LIGHT','LIGHT–MID','MID–SHADOW','REFLECTED','DEEPEST'];shell('Paint the environment into the form','The grayscale reference is already solved. Use all six blended colors on the watercolor sphere, then add the complement to its reflected light and shadow.',`<div class="form-practice"><div class="action-demo paint-demo"><b>HOW TO PAINT</b><span><i>1</i> Choose a blend</span><strong>→</strong><span><i>2</i> Tap or drag it onto the matching curved layer</span><strong>→</strong><span><i>3</i> Complete all six</span></div><div class="comp-palette">${palette.map((c,i)=>`<button draggable="true" data-color="${i}" class="${selected===i?'on':''}" style="--c:${c}"><i></i><small>${names[i]}</small></button>`).join('')}</div><div class="compare-forms"><section><b>MONOCHROME GUIDE</b><p>Six curved value layers turn the sphere.</p><div class="shape-paper">${sphere(['#f5f4f2','#dddcd9','#bcb9b8','#918e90','#666367','#36343a'])}</div></section><div class="compare-arrow">→</div><section><b>YOUR WATERCOLOR STUDY</b><p>${selected==null?'Step 1: choose or drag one blended color from above.':'Now tap its matching curved layer, or drag the color directly onto it.'}</p><div class="shape-paper">${sphere(colors,true)}</div><div class="comp-layer-guides">${names.map((n,i)=>`<button data-layer-guide="${i}" class="${colors[i]?'painted':''}" style="--fill:${colors[i]||'#ddd'}">${n}</button>`).join('')}</div></section></div>${done?`<div class="practice-check"><button class="btn" data-refine>Done painting · Reveal reflected light</button></div>`:''}</div>`,back());document.querySelector('[data-back]').onclick=()=>go(2);document.querySelectorAll('[data-color]').forEach(b=>{b.onclick=()=>{selected=+b.dataset.color;render()};b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.color)});const apply=(b,colorIndex=selected)=>{if(colorIndex==null||colorIndex==='')return say('Step 1: choose a blended color first.');selected=+colorIndex;const i=+(b.dataset.layerGuide??b.dataset.layer);state.paint[i]=palette[selected];save();tone(480-selected*35);render()};document.querySelectorAll('.interactive [data-layer], [data-layer-guide]').forEach(b=>{b.onclick=()=>apply(b);b.ondragover=e=>{e.preventDefault();b.classList.add('drag-ready')};b.ondragleave=()=>b.classList.remove('drag-ready');b.ondrop=e=>{e.preventDefault();apply(b,e.dataTransfer.getData('text/plain'))}});document.querySelector('[data-refine]')?.addEventListener('click',()=>{state.refined=true;save();go(4)})}
function reflect(){const p=PAIRS[state.pair],colors=Array.from({length:6},(_,i)=>state.paint[i]);shell('The shadow can carry the environment','The opposite color now appears softly in the lower reflection and cast shadow. It supports the local color—it does not replace it.',`<div class="reflection-result"><div class="shape-paper">${sphere(colors)}</div><div><div class="eyebrow">YOUR COLOR RELATIONSHIP</div><h3>${p.name}</h3><p>The form keeps its own color family. The complement enters gradually through blending, reflected light and shadow.</p><div class="reflection-key"><i style="--c:${p.base}"></i><span>local color</span><strong>+</strong><i style="--c:${p.opposite}"></i><span>environment</span></div></div></div>`,next(true,'Watch the teacher process'));nav()}
function teacher(){shell('Now watch it happen on paper','The teacher demonstration is a reference, not a standard answer. Look for soft transitions—never a hard half-and-half split.',`<div class="teacher-reference"><div class="teacher-video"><video src="../color-practice-shapes/assets/complement-process.mp4" poster="../color-practice-shapes/assets/complements-demo.jpg" muted controls playsinline></video><span>Classroom process · muted</span></div><div class="reference-note"><div class="eyebrow">LOOK FOR</div><ol><li>Six gradual mixtures</li><li>Soft watercolor edges</li><li>Complementary reflected light</li><li>Environmental color in the shadow</li></ol></div></div>`,next(true,'Finish the lesson'));nav()}
function finish(){state.complete=true;localStorage.setItem(C.completeKey,'true');save();shell('You gave color an environment','You used a complement to turn form, reflect light and connect the shadow to the space around it.',`<div class="neighbor-finish"><div class="shape-paper">${sphere(Array.from({length:6},(_,i)=>state.paint[i]))}</div><div><div class="eyebrow">LESSON COMPLETE ✓</div><h3>Opposites can belong together.</h3><p>You blended them instead of separating them.</p></div></div>`,`<button class="btn secondary" data-replay>Practice again</button><a class="btn" href="${C.nextHref}">${C.nextLabel} →</a>`);document.querySelector('[data-replay]').onclick=()=>{state={version:2,page:0,found:[],pair:0,mixed:[],paint:{},refined:false,complete:true};save();render()}}
function render(){if(state.page===0)return intro();if(state.page===1)return pairs();if(state.page===2)return blend();if(state.page===3)return paint();if(state.page===4)return reflect();if(state.page===5)return teacher();return finish()}
render();
})();
